<?php



/**
 * This class defines the structure of the 'tw_subscription_email' table.
 *
 *
 * This class was autogenerated by Propel 1.6.6 on:
 *
 * Thu Sep 27 23:40:08 2012
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    propel.generator.plugins.twSubscriptionPlugin.lib.model.map
 */
class twSubscriptionEmailTableMap extends TableMap
{

    /**
     * The (dot-path) name of this class
     */
    const CLASS_NAME = 'plugins.twSubscriptionPlugin.lib.model.map.twSubscriptionEmailTableMap';

    /**
     * Initialize the table attributes, columns and validators
     * Relations are not initialized by this method since they are lazy loaded
     *
     * @return void
     * @throws PropelException
     */
    public function initialize()
    {
        // attributes
        $this->setName('tw_subscription_email');
        $this->setPhpName('twSubscriptionEmail');
        $this->setClassname('twSubscriptionEmail');
        $this->setPackage('plugins.twSubscriptionPlugin.lib.model');
        $this->setUseIdGenerator(true);
        // columns
        $this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
        $this->addForeignKey('LIST_ID', 'ListId', 'INTEGER', 'tw_subscription_list', 'ID', true, null, null);
        $this->addForeignKey('STATUS_ID', 'StatusId', 'INTEGER', 'tw_subscription_status', 'ID', true, null, null);
        $this->addColumn('REMAIL', 'Remail', 'VARCHAR', true, 250, null);
        $this->addColumn('RNAME', 'Rname', 'VARCHAR', false, 250, null);
        $this->addColumn('EXPIRES', 'Expires', 'TIMESTAMP', false, null, null);
        $this->addColumn('AUTH_KEY', 'AuthKey', 'VARCHAR', true, 40, null);
        $this->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null, null);
        // validators
    } // initialize()

    /**
     * Build the RelationMap objects for this table relationships
     */
    public function buildRelations()
    {
        $this->addRelation('twSubscriptionList', 'twSubscriptionList', RelationMap::MANY_TO_ONE, array('list_id' => 'id', ), 'CASCADE', null);
        $this->addRelation('twSubscriptionStatus', 'twSubscriptionStatus', RelationMap::MANY_TO_ONE, array('status_id' => 'id', ), 'CASCADE', null);
    } // buildRelations()

    /**
     *
     * Gets the list of behaviors registered for this table
     *
     * @return array Associative array (name => parameters) of behaviors
     */
    public function getBehaviors()
    {
        return array(
            'symfony' => array('form' => 'true', 'filter' => 'true', ),
            'symfony_behaviors' => array(),
            'symfony_timestampable' => array('create_column' => 'created_at', ),
        );
    } // getBehaviors()

} // twSubscriptionEmailTableMap
