<?php



/**
 * This class defines the structure of the 'tw_subscription_status' table.
 *
 *
 * This class was autogenerated by Propel 1.6.6 on:
 *
 * Thu Sep 27 23:40:08 2012
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    propel.generator.plugins.twSubscriptionPlugin.lib.model.map
 */
class twSubscriptionStatusTableMap extends TableMap
{

    /**
     * The (dot-path) name of this class
     */
    const CLASS_NAME = 'plugins.twSubscriptionPlugin.lib.model.map.twSubscriptionStatusTableMap';

    /**
     * Initialize the table attributes, columns and validators
     * Relations are not initialized by this method since they are lazy loaded
     *
     * @return void
     * @throws PropelException
     */
    public function initialize()
    {
        // attributes
        $this->setName('tw_subscription_status');
        $this->setPhpName('twSubscriptionStatus');
        $this->setClassname('twSubscriptionStatus');
        $this->setPackage('plugins.twSubscriptionPlugin.lib.model');
        $this->setUseIdGenerator(true);
        // columns
        $this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
        $this->addColumn('CODE', 'Code', 'VARCHAR', true, 250, null);
        // validators
    } // initialize()

    /**
     * Build the RelationMap objects for this table relationships
     */
    public function buildRelations()
    {
        $this->addRelation('twSubscriptionStatusI18n', 'twSubscriptionStatusI18n', RelationMap::ONE_TO_MANY, array('id' => 'id', ), null, null, 'twSubscriptionStatusI18ns');
        $this->addRelation('twSubscriptionEmail', 'twSubscriptionEmail', RelationMap::ONE_TO_MANY, array('id' => 'status_id', ), 'CASCADE', null, 'twSubscriptionEmails');
    } // buildRelations()

    /**
     *
     * Gets the list of behaviors registered for this table
     *
     * @return array Associative array (name => parameters) of behaviors
     */
    public function getBehaviors()
    {
        return array(
            'symfony' => array('form' => 'true', 'filter' => 'true', ),
            'symfony_behaviors' => array(),
            'symfony_i18n' => array('i18n_table' => 'tw_subscription_status_i18n', ),
        );
    } // getBehaviors()

} // twSubscriptionStatusTableMap
