<?php



/**
 * This class defines the structure of the 'tw_subscription_mailing' table.
 *
 *
 * This class was autogenerated by Propel 1.6.6 on:
 *
 * Thu Sep 27 23:40:08 2012
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    propel.generator.plugins.twSubscriptionPlugin.lib.model.map
 */
class twSubscriptionMailingTableMap extends TableMap
{

    /**
     * The (dot-path) name of this class
     */
    const CLASS_NAME = 'plugins.twSubscriptionPlugin.lib.model.map.twSubscriptionMailingTableMap';

    /**
     * Initialize the table attributes, columns and validators
     * Relations are not initialized by this method since they are lazy loaded
     *
     * @return void
     * @throws PropelException
     */
    public function initialize()
    {
        // attributes
        $this->setName('tw_subscription_mailing');
        $this->setPhpName('twSubscriptionMailing');
        $this->setClassname('twSubscriptionMailing');
        $this->setPackage('plugins.twSubscriptionPlugin.lib.model');
        $this->setUseIdGenerator(true);
        // columns
        $this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
        $this->addForeignKey('LIST_ID', 'ListId', 'INTEGER', 'tw_subscription_list', 'ID', true, null, null);
        $this->addForeignKey('MESSAGE_ID', 'MessageId', 'INTEGER', 'tw_subscription_message', 'ID', true, null, null);
        $this->addColumn('TIME_TO_SEND', 'TimeToSend', 'TIMESTAMP', true, null, null);
        $this->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null, null);
        // validators
    } // initialize()

    /**
     * Build the RelationMap objects for this table relationships
     */
    public function buildRelations()
    {
        $this->addRelation('twSubscriptionList', 'twSubscriptionList', RelationMap::MANY_TO_ONE, array('list_id' => 'id', ), 'CASCADE', null);
        $this->addRelation('twSubscriptionMessage', 'twSubscriptionMessage', RelationMap::MANY_TO_ONE, array('message_id' => 'id', ), 'CASCADE', null);
        $this->addRelation('twSubscriptionMailQueue', 'twSubscriptionMailQueue', RelationMap::ONE_TO_MANY, array('id' => 'mailing_id', ), 'CASCADE', null, 'twSubscriptionMailQueues');
        $this->addRelation('twSubscriptionMailSent', 'twSubscriptionMailSent', RelationMap::ONE_TO_MANY, array('id' => 'mailing_id', ), 'CASCADE', null, 'twSubscriptionMailSents');
    } // buildRelations()

    /**
     *
     * Gets the list of behaviors registered for this table
     *
     * @return array Associative array (name => parameters) of behaviors
     */
    public function getBehaviors()
    {
        return array(
            'symfony' => array('form' => 'true', 'filter' => 'true', ),
            'symfony_behaviors' => array(),
            'symfony_timestampable' => array('create_column' => 'created_at', ),
        );
    } // getBehaviors()

} // twSubscriptionMailingTableMap
