<?php



/**
 * This class defines the structure of the 'tw_subscription_template' table.
 *
 *
 * This class was autogenerated by Propel 1.6.6 on:
 *
 * Thu Sep 27 23:40:08 2012
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    propel.generator.plugins.twSubscriptionPlugin.lib.model.map
 */
class twSubscriptionTemplateTableMap extends TableMap
{

    /**
     * The (dot-path) name of this class
     */
    const CLASS_NAME = 'plugins.twSubscriptionPlugin.lib.model.map.twSubscriptionTemplateTableMap';

    /**
     * Initialize the table attributes, columns and validators
     * Relations are not initialized by this method since they are lazy loaded
     *
     * @return void
     * @throws PropelException
     */
    public function initialize()
    {
        // attributes
        $this->setName('tw_subscription_template');
        $this->setPhpName('twSubscriptionTemplate');
        $this->setClassname('twSubscriptionTemplate');
        $this->setPackage('plugins.twSubscriptionPlugin.lib.model');
        $this->setUseIdGenerator(true);
        // columns
        $this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
        $this->addForeignKey('TYPE_ID', 'TypeId', 'INTEGER', 'tw_subscription_message_type', 'ID', true, null, null);
        $this->addColumn('TNAME', 'Tname', 'VARCHAR', true, 50, null);
        $this->addColumn('TDATA', 'Tdata', 'LONGVARCHAR', true, null, null);
        // validators
    } // initialize()

    /**
     * Build the RelationMap objects for this table relationships
     */
    public function buildRelations()
    {
        $this->addRelation('twSubscriptionMessageType', 'twSubscriptionMessageType', RelationMap::MANY_TO_ONE, array('type_id' => 'id', ), 'CASCADE', null);
        $this->addRelation('twSubscriptionList', 'twSubscriptionList', RelationMap::ONE_TO_MANY, array('id' => 'template_id', ), 'SET NULL', null, 'twSubscriptionLists');
    } // buildRelations()

    /**
     *
     * Gets the list of behaviors registered for this table
     *
     * @return array Associative array (name => parameters) of behaviors
     */
    public function getBehaviors()
    {
        return array(
            'symfony' => array('form' => 'true', 'filter' => 'true', ),
            'symfony_behaviors' => array(),
        );
    } // getBehaviors()

} // twSubscriptionTemplateTableMap
