<?php


/**
 * Base class that represents a row from the 'tw_subscription_status' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.6 on:
 *
 * Thu Sep 27 23:40:08 2012
 *
 * @package    propel.generator.plugins.twSubscriptionPlugin.lib.model.om
 */
abstract class BasetwSubscriptionStatus extends BaseObject 
{

    /**
     * Peer class name
     */
    const PEER = 'twSubscriptionStatusPeer';

    /**
     * The Peer class.
     * Instance provides a convenient way of calling static methods on a class
     * that calling code may not be able to identify.
     * @var        twSubscriptionStatusPeer
     */
    protected static $peer;

    /**
     * The flag var to prevent infinit loop in deep copy
     * @var       boolean
     */
    protected $startCopy = false;

    /**
     * The value for the id field.
     * @var        int
     */
    protected $id;

    /**
     * The value for the code field.
     * @var        string
     */
    protected $code;

    /**
     * @var        PropelObjectCollection|twSubscriptionStatusI18n[] Collection to store aggregation of twSubscriptionStatusI18n objects.
     */
    protected $colltwSubscriptionStatusI18ns;

    /**
     * @var        PropelObjectCollection|twSubscriptionEmail[] Collection to store aggregation of twSubscriptionEmail objects.
     */
    protected $colltwSubscriptionEmails;

    /**
     * Flag to prevent endless save loop, if this object is referenced
     * by another object which falls in this transaction.
     * @var        boolean
     */
    protected $alreadyInSave = false;

    /**
     * Flag to prevent endless validation loop, if this object is referenced
     * by another object which falls in this transaction.
     * @var        boolean
     */
    protected $alreadyInValidation = false;

	// symfony_i18n behavior
	
	/**
	 * @var string The value for the culture field
	 */
	protected $culture = null;
	
	/**
	 * @var array Current I18N objects
	 */
	protected $current_i18n = array();

    /**
     * An array of objects scheduled for deletion.
     * @var		PropelObjectCollection
     */
    protected $twSubscriptionStatusI18nsScheduledForDeletion = null;

    /**
     * An array of objects scheduled for deletion.
     * @var		PropelObjectCollection
     */
    protected $twSubscriptionEmailsScheduledForDeletion = null;

    /**
     * Get the [id] column value.
     * 
     * @return   int
     */
    public function getId()
    {

        return $this->id;
    }

    /**
     * Get the [code] column value.
     * 
     * @return   string
     */
    public function getCode()
    {

        return $this->code;
    }

    /**
     * Set the value of [id] column.
     * 
     * @param      int $v new value
     * @return   twSubscriptionStatus The current object (for fluent API support)
     */
    public function setId($v)
    {
        if ($v !== null) {
            $v = (int) $v;
        }

        if ($this->id !== $v) {
            $this->id = $v;
            $this->modifiedColumns[] = twSubscriptionStatusPeer::ID;
        }


        return $this;
    } // setId()

    /**
     * Set the value of [code] column.
     * 
     * @param      string $v new value
     * @return   twSubscriptionStatus The current object (for fluent API support)
     */
    public function setCode($v)
    {
        if ($v !== null) {
            $v = (string) $v;
        }

        if ($this->code !== $v) {
            $this->code = $v;
            $this->modifiedColumns[] = twSubscriptionStatusPeer::CODE;
        }


        return $this;
    } // setCode()

    /**
     * Indicates whether the columns in this object are only set to default values.
     *
     * This method can be used in conjunction with isModified() to indicate whether an object is both
     * modified _and_ has some values set which are non-default.
     *
     * @return boolean Whether the columns in this object are only been set with default values.
     */
    public function hasOnlyDefaultValues()
    {
        // otherwise, everything was equal, so return TRUE
        return true;
    } // hasOnlyDefaultValues()

    /**
     * Hydrates (populates) the object variables with values from the database resultset.
     *
     * An offset (0-based "start column") is specified so that objects can be hydrated
     * with a subset of the columns in the resultset rows.  This is needed, for example,
     * for results of JOIN queries where the resultset row includes columns from two or
     * more tables.
     *
     * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
     * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
     * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
     * @return int             next starting column
     * @throws PropelException - Any caught Exception will be rewrapped as a PropelException.
     */
    public function hydrate($row, $startcol = 0, $rehydrate = false)
    {
        try {

            $this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
            $this->code = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
            $this->resetModified();

            $this->setNew(false);

            if ($rehydrate) {
                $this->ensureConsistency();
            }

            return $startcol + 2; // 2 = twSubscriptionStatusPeer::NUM_HYDRATE_COLUMNS.

        } catch (Exception $e) {
            throw new PropelException("Error populating twSubscriptionStatus object", $e);
        }
    }

    /**
     * Checks and repairs the internal consistency of the object.
     *
     * This method is executed after an already-instantiated object is re-hydrated
     * from the database.  It exists to check any foreign keys to make sure that
     * the objects related to the current object are correct based on foreign key.
     *
     * You can override this method in the stub class, but you should always invoke
     * the base method from the overridden method (i.e. parent::ensureConsistency()),
     * in case your model changes.
     *
     * @throws PropelException
     */
    public function ensureConsistency()
    {

    } // ensureConsistency

    /**
     * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
     *
     * This will only work if the object has been saved and has a valid primary key set.
     *
     * @param      boolean $deep (optional) Whether to also de-associated any related objects.
     * @param      PropelPDO $con (optional) The PropelPDO connection to use.
     * @return void
     * @throws PropelException - if this object is deleted, unsaved or doesn't have pk match in db
     */
    public function reload($deep = false, PropelPDO $con = null)
    {
        if ($this->isDeleted()) {
            throw new PropelException("Cannot reload a deleted object.");
        }

        if ($this->isNew()) {
            throw new PropelException("Cannot reload an unsaved object.");
        }

        if ($con === null) {
            $con = Propel::getConnection(twSubscriptionStatusPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }

        // We don't need to alter the object instance pool; we're just modifying this instance
        // already in the pool.

        $stmt = twSubscriptionStatusPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
        $row = $stmt->fetch(PDO::FETCH_NUM);
        $stmt->closeCursor();
        if (!$row) {
            throw new PropelException('Cannot find matching row in the database to reload object values.');
        }
        $this->hydrate($row, 0, true); // rehydrate

        if ($deep) {  // also de-associate any related objects?

            $this->colltwSubscriptionStatusI18ns = null;

            $this->colltwSubscriptionEmails = null;

        } // if (deep)
    }

    /**
     * Removes this object from datastore and sets delete attribute.
     *
     * @param      PropelPDO $con
     * @return void
     * @throws PropelException
     * @throws Exception
     * @see        BaseObject::setDeleted()
     * @see        BaseObject::isDeleted()
     */
    public function delete(PropelPDO $con = null)
    {
        if ($this->isDeleted()) {
            throw new PropelException("This object has already been deleted.");
        }

        if ($con === null) {
            $con = Propel::getConnection(twSubscriptionStatusPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
        }

        $con->beginTransaction();
        try {
            $deleteQuery = twSubscriptionStatusQuery::create()
                ->filterByPrimaryKey($this->getPrimaryKey());
            $ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BasetwSubscriptionStatus:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			    return;
			  }
			}

            if ($ret) {
                $deleteQuery->delete($con);
                $this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BasetwSubscriptionStatus:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

                $con->commit();
                $this->setDeleted(true);
            } else {
                $con->commit();
            }
        } catch (Exception $e) {
            $con->rollBack();
            throw $e;
        }
    }

    /**
     * Persists this object to the database.
     *
     * If the object is new, it inserts it; otherwise an update is performed.
     * All modified related objects will also be persisted in the doSave()
     * method.  This method wraps all precipitate database operations in a
     * single transaction.
     *
     * @param      PropelPDO $con
     * @return int             The number of rows affected by this insert/update and any referring fk objects' save() operations.
     * @throws PropelException
     * @throws Exception
     * @see        doSave()
     */
    public function save(PropelPDO $con = null)
    {
        if ($this->isDeleted()) {
            throw new PropelException("You cannot save an object that has been deleted.");
        }

        if ($con === null) {
            $con = Propel::getConnection(twSubscriptionStatusPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
        }

        $con->beginTransaction();
        $isInsert = $this->isNew();
        try {
            $ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BasetwSubscriptionStatus:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			  	$con->commit();
			    return $affectedRows;
			  }
			}

            if ($isInsert) {
                $ret = $ret && $this->preInsert($con);
            } else {
                $ret = $ret && $this->preUpdate($con);
            }
            if ($ret) {
                $affectedRows = $this->doSave($con);
                if ($isInsert) {
                    $this->postInsert($con);
                } else {
                    $this->postUpdate($con);
                }
                $this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BasetwSubscriptionStatus:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

                twSubscriptionStatusPeer::addInstanceToPool($this);
            } else {
                $affectedRows = 0;
            }
            $con->commit();

            return $affectedRows;
        } catch (Exception $e) {
            $con->rollBack();
            throw $e;
        }
    }

    /**
     * Performs the work of inserting or updating the row in the database.
     *
     * If the object is new, it inserts it; otherwise an update is performed.
     * All related objects are also updated in this method.
     *
     * @param      PropelPDO $con
     * @return int             The number of rows affected by this insert/update and any referring fk objects' save() operations.
     * @throws PropelException
     * @see        save()
     */
    protected function doSave(PropelPDO $con)
    {
        $affectedRows = 0; // initialize var to track total num of affected rows
        if (!$this->alreadyInSave) {
            $this->alreadyInSave = true;

            if ($this->isNew() || $this->isModified()) {
                // persist changes
                if ($this->isNew()) {
                    $this->doInsert($con);
                } else {
                    $this->doUpdate($con);
                }
                $affectedRows += 1;
                $this->resetModified();
            }

            if ($this->twSubscriptionStatusI18nsScheduledForDeletion !== null) {
                if (!$this->twSubscriptionStatusI18nsScheduledForDeletion->isEmpty()) {
                    twSubscriptionStatusI18nQuery::create()
                        ->filterByPrimaryKeys($this->twSubscriptionStatusI18nsScheduledForDeletion->getPrimaryKeys(false))
                        ->delete($con);
                    $this->twSubscriptionStatusI18nsScheduledForDeletion = null;
                }
            }

            if ($this->colltwSubscriptionStatusI18ns !== null) {
                foreach ($this->colltwSubscriptionStatusI18ns as $referrerFK) {
          $referrerFK->settwSubscriptionStatus($this);
                    if (!$referrerFK->isDeleted()) {
                        $affectedRows += $referrerFK->save($con);
                    }
                }
            }

            if ($this->twSubscriptionEmailsScheduledForDeletion !== null) {
                if (!$this->twSubscriptionEmailsScheduledForDeletion->isEmpty()) {
                    twSubscriptionEmailQuery::create()
                        ->filterByPrimaryKeys($this->twSubscriptionEmailsScheduledForDeletion->getPrimaryKeys(false))
                        ->delete($con);
                    $this->twSubscriptionEmailsScheduledForDeletion = null;
                }
            }

            if ($this->colltwSubscriptionEmails !== null) {
                foreach ($this->colltwSubscriptionEmails as $referrerFK) {
                    if (!$referrerFK->isDeleted()) {
                        $affectedRows += $referrerFK->save($con);
                    }
                }
            }

            $this->alreadyInSave = false;

        }

        return $affectedRows;
    } // doSave()

    /**
     * Insert the row in the database.
     *
     * @param      PropelPDO $con
     *
     * @throws PropelException
     * @see        doSave()
     */
    protected function doInsert(PropelPDO $con)
    {
        $modifiedColumns = array();
        $index = 0;

        $this->modifiedColumns[] = twSubscriptionStatusPeer::ID;
        if (null !== $this->id) {
            throw new PropelException('Cannot insert a value for auto-increment primary key (' . twSubscriptionStatusPeer::ID . ')');
        }

         // check the columns in natural order for more readable SQL queries
        if ($this->isColumnModified(twSubscriptionStatusPeer::ID)) {
            $modifiedColumns[':p' . $index++]  = '`ID`';
        }
        if ($this->isColumnModified(twSubscriptionStatusPeer::CODE)) {
            $modifiedColumns[':p' . $index++]  = '`CODE`';
        }

        $sql = sprintf(
            'INSERT INTO `tw_subscription_status` (%s) VALUES (%s)',
            implode(', ', $modifiedColumns),
            implode(', ', array_keys($modifiedColumns))
        );

        try {
            $stmt = $con->prepare($sql);
            foreach ($modifiedColumns as $identifier => $columnName) {
                switch ($columnName) {
                    case '`ID`':
						$stmt->bindValue($identifier, $this->id, PDO::PARAM_INT);
                        break;
                    case '`CODE`':
						$stmt->bindValue($identifier, $this->code, PDO::PARAM_STR);
                        break;
                }
            }
            $stmt->execute();
        } catch (Exception $e) {
            Propel::log($e->getMessage(), Propel::LOG_ERR);
            throw new PropelException(sprintf('Unable to execute INSERT statement [%s]', $sql), $e);
        }

        try {
			$pk = $con->lastInsertId();
        } catch (Exception $e) {
            throw new PropelException('Unable to get autoincrement id.', $e);
        }
        $this->setId($pk);

        $this->setNew(false);
    }

    /**
     * Update the row in the database.
     *
     * @param      PropelPDO $con
     *
     * @see        doSave()
     */
    protected function doUpdate(PropelPDO $con)
    {
        $selectCriteria = $this->buildPkeyCriteria();
        $valuesCriteria = $this->buildCriteria();
        BasePeer::doUpdate($selectCriteria, $valuesCriteria, $con);
    }

    /**
     * Array of ValidationFailed objects.
     * @var        array ValidationFailed[]
     */
    protected $validationFailures = array();

    /**
     * Gets any ValidationFailed objects that resulted from last call to validate().
     *
     *
     * @return array ValidationFailed[]
     * @see        validate()
     */
    public function getValidationFailures()
    {
        return $this->validationFailures;
    }

    /**
     * Validates the objects modified field values and all objects related to this table.
     *
     * If $columns is either a column name or an array of column names
     * only those columns are validated.
     *
     * @param      mixed $columns Column name or an array of column names.
     * @return boolean Whether all columns pass validation.
     * @see        doValidate()
     * @see        getValidationFailures()
     */
    public function validate($columns = null)
    {
        $res = $this->doValidate($columns);
        if ($res === true) {
            $this->validationFailures = array();

            return true;
        } else {
            $this->validationFailures = $res;

            return false;
        }
    }

    /**
     * This function performs the validation work for complex object models.
     *
     * In addition to checking the current object, all related objects will
     * also be validated.  If all pass then <code>true</code> is returned; otherwise
     * an aggreagated array of ValidationFailed objects will be returned.
     *
     * @param      array $columns Array of column names to validate.
     * @return mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
     */
    protected function doValidate($columns = null)
    {
        if (!$this->alreadyInValidation) {
            $this->alreadyInValidation = true;
            $retval = null;

            $failureMap = array();


            if (($retval = twSubscriptionStatusPeer::doValidate($this, $columns)) !== true) {
                $failureMap = array_merge($failureMap, $retval);
            }


                if ($this->colltwSubscriptionStatusI18ns !== null) {
                    foreach ($this->colltwSubscriptionStatusI18ns as $referrerFK) {
          $referrerFK->settwSubscriptionStatus($this);
                        if (!$referrerFK->validate($columns)) {
                            $failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
                        }
                    }
                }

                if ($this->colltwSubscriptionEmails !== null) {
                    foreach ($this->colltwSubscriptionEmails as $referrerFK) {
                        if (!$referrerFK->validate($columns)) {
                            $failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
                        }
                    }
                }


            $this->alreadyInValidation = false;
        }

        return (!empty($failureMap) ? $failureMap : true);
    }

    /**
     * Retrieves a field from the object by name passed in as a string.
     *
     * @param      string $name name
     * @param      string $type The type of fieldname the $name is of:
     *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
     *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
     *                     Defaults to BasePeer::TYPE_PHPNAME
     * @return mixed Value of field.
     */
    public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
    {
        $pos = twSubscriptionStatusPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
        $field = $this->getByPosition($pos);

        return $field;
    }

    /**
     * Retrieves a field from the object by Position as specified in the xml schema.
     * Zero-based.
     *
     * @param      int $pos position in xml schema
     * @return mixed Value of field at $pos
     */
    public function getByPosition($pos)
    {
        switch ($pos) {
            case 0:
                return $this->getId();
                break;
            case 1:
                return $this->getCode();
                break;
            default:
                return null;
                break;
        } // switch()
    }

    /**
     * Exports the object as an array.
     *
     * You can specify the key type of the array by passing one of the class
     * type constants.
     *
     * @param     string  $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
     *                    BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
     *                    Defaults to BasePeer::TYPE_PHPNAME.
     * @param     boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns. Defaults to TRUE.
     * @param     array $alreadyDumpedObjects List of objects to skip to avoid recursion
     * @param     boolean $includeForeignObjects (optional) Whether to include hydrated related objects. Default to FALSE.
     *
     * @return array an associative array containing the field names (as keys) and field values
     */
    public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true, $alreadyDumpedObjects = array(), $includeForeignObjects = false)
    {
        if (isset($alreadyDumpedObjects['twSubscriptionStatus'][$this->getPrimaryKey()])) {
            return '*RECURSION*';
        }
        $alreadyDumpedObjects['twSubscriptionStatus'][$this->getPrimaryKey()] = true;
        $keys = twSubscriptionStatusPeer::getFieldNames($keyType);
        $result = array(
            $keys[0] => $this->getId(),
            $keys[1] => $this->getCode(),
        );
        if ($includeForeignObjects) {
            if (null !== $this->colltwSubscriptionStatusI18ns) {
                $result['twSubscriptionStatusI18ns'] = $this->colltwSubscriptionStatusI18ns->toArray(null, true, $keyType, $includeLazyLoadColumns, $alreadyDumpedObjects);
            }
            if (null !== $this->colltwSubscriptionEmails) {
                $result['twSubscriptionEmails'] = $this->colltwSubscriptionEmails->toArray(null, true, $keyType, $includeLazyLoadColumns, $alreadyDumpedObjects);
            }
        }

        return $result;
    }

    /**
     * Sets a field from the object by name passed in as a string.
     *
     * @param      string $name peer name
     * @param      mixed $value field value
     * @param      string $type The type of fieldname the $name is of:
     *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
     *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
     *                     Defaults to BasePeer::TYPE_PHPNAME
     * @return void
     */
    public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
    {
        $pos = twSubscriptionStatusPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);

        $this->setByPosition($pos, $value);
    }

    /**
     * Sets a field from the object by Position as specified in the xml schema.
     * Zero-based.
     *
     * @param      int $pos position in xml schema
     * @param      mixed $value field value
     * @return void
     */
    public function setByPosition($pos, $value)
    {
        switch ($pos) {
            case 0:
                $this->setId($value);
                break;
            case 1:
                $this->setCode($value);
                break;
        } // switch()
    }

    /**
     * Populates the object using an array.
     *
     * This is particularly useful when populating an object from one of the
     * request arrays (e.g. $_POST).  This method goes through the column
     * names, checking to see whether a matching key exists in populated
     * array. If so the setByName() method is called for that column.
     *
     * You can specify the key type of the array by additionally passing one
     * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
     * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
     * The default key type is the column's BasePeer::TYPE_PHPNAME
     *
     * @param      array  $arr     An array to populate the object from.
     * @param      string $keyType The type of keys the array uses.
     * @return void
     */
    public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
    {
        $keys = twSubscriptionStatusPeer::getFieldNames($keyType);

        if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
        if (array_key_exists($keys[1], $arr)) $this->setCode($arr[$keys[1]]);
    }

    /**
     * Build a Criteria object containing the values of all modified columns in this object.
     *
     * @return Criteria The Criteria object containing all modified values.
     */
    public function buildCriteria()
    {
        $criteria = new Criteria(twSubscriptionStatusPeer::DATABASE_NAME);

        if ($this->isColumnModified(twSubscriptionStatusPeer::ID)) $criteria->add(twSubscriptionStatusPeer::ID, $this->id);
        if ($this->isColumnModified(twSubscriptionStatusPeer::CODE)) $criteria->add(twSubscriptionStatusPeer::CODE, $this->code);

        return $criteria;
    }

    /**
     * Builds a Criteria object containing the primary key for this object.
     *
     * Unlike buildCriteria() this method includes the primary key values regardless
     * of whether or not they have been modified.
     *
     * @return Criteria The Criteria object containing value(s) for primary key(s).
     */
    public function buildPkeyCriteria()
    {
        $criteria = new Criteria(twSubscriptionStatusPeer::DATABASE_NAME);
        $criteria->add(twSubscriptionStatusPeer::ID, $this->id);

        return $criteria;
    }

    /**
     * Returns the primary key for this object (row).
     * @return   int
     */
    public function getPrimaryKey()
    {
        return $this->getId();
    }

    /**
     * Generic method to set the primary key (id column).
     *
     * @param       int $key Primary key.
     * @return void
     */
    public function setPrimaryKey($key)
    {
        $this->setId($key);
    }

    /**
     * Returns true if the primary key for this object is null.
     * @return boolean
     */
    public function isPrimaryKeyNull()
    {

        return null === $this->getId();
    }

    /**
     * Sets contents of passed object to values from current object.
     *
     * If desired, this method can also make copies of all associated (fkey referrers)
     * objects.
     *
     * @param      object $copyObj An object of twSubscriptionStatus (or compatible) type.
     * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
     * @param      boolean $makeNew Whether to reset autoincrement PKs and make the object new.
     * @throws PropelException
     */
    public function copyInto($copyObj, $deepCopy = false, $makeNew = true)
    {
        $copyObj->setCode($this->getCode());

        if ($deepCopy && !$this->startCopy) {
            // important: temporarily setNew(false) because this affects the behavior of
            // the getter/setter methods for fkey referrer objects.
            $copyObj->setNew(false);
            // store object hash to prevent cycle
            $this->startCopy = true;

            foreach ($this->gettwSubscriptionStatusI18ns() as $relObj) {
                if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
                    $copyObj->addtwSubscriptionStatusI18n($relObj->copy($deepCopy));
                }
            }

            foreach ($this->gettwSubscriptionEmails() as $relObj) {
                if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
                    $copyObj->addtwSubscriptionEmail($relObj->copy($deepCopy));
                }
            }

            //unflag object copy
            $this->startCopy = false;
        } // if ($deepCopy)

        if ($makeNew) {
            $copyObj->setNew(true);
            $copyObj->setId(NULL); // this is a auto-increment column, so set to default value
        }
    }

    /**
     * Makes a copy of this object that will be inserted as a new row in table when saved.
     * It creates a new object filling in the simple attributes, but skipping any primary
     * keys that are defined for the table.
     *
     * If desired, this method can also make copies of all associated (fkey referrers)
     * objects.
     *
     * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
     * @return                 twSubscriptionStatus Clone of current object.
     * @throws PropelException
     */
    public function copy($deepCopy = false)
    {
        // we use get_class(), because this might be a subclass
        $clazz = get_class($this);
        $copyObj = new $clazz();
        $this->copyInto($copyObj, $deepCopy);

        return $copyObj;
    }

    /**
     * Returns a peer instance associated with this om.
     *
     * Since Peer classes are not to have any instance attributes, this method returns the
     * same instance for all member of this class. The method could therefore
     * be static, but this would prevent one from overriding the behavior.
     *
     * @return   twSubscriptionStatusPeer
     */
    public function getPeer()
    {
        if (self::$peer === null) {
            self::$peer = new twSubscriptionStatusPeer();
        }

        return self::$peer;
    }


    /**
     * Initializes a collection based on the name of a relation.
     * Avoids crafting an 'init[$relationName]s' method name
     * that wouldn't work when StandardEnglishPluralizer is used.
     *
     * @param      string $relationName The name of the relation to initialize
     * @return void
     */
    public function initRelation($relationName)
    {
        if ('twSubscriptionStatusI18n' == $relationName) {
            $this->inittwSubscriptionStatusI18ns();
        }
        if ('twSubscriptionEmail' == $relationName) {
            $this->inittwSubscriptionEmails();
        }
    }

    /**
     * Clears out the colltwSubscriptionStatusI18ns collection
     *
     * This does not modify the database; however, it will remove any associated objects, causing
     * them to be refetched by subsequent calls to accessor method.
     *
     * @return void
     * @see        addtwSubscriptionStatusI18ns()
     */
    public function cleartwSubscriptionStatusI18ns()
    {
        $this->colltwSubscriptionStatusI18ns = null; // important to set this to NULL since that means it is uninitialized
    }

    /**
     * Initializes the colltwSubscriptionStatusI18ns collection.
     *
     * By default this just sets the colltwSubscriptionStatusI18ns collection to an empty array (like clearcolltwSubscriptionStatusI18ns());
     * however, you may wish to override this method in your stub class to provide setting appropriate
     * to your application -- for example, setting the initial array to the values stored in database.
     *
     * @param      boolean $overrideExisting If set to true, the method call initializes
     *                                        the collection even if it is not empty
     *
     * @return void
     */
    public function inittwSubscriptionStatusI18ns($overrideExisting = true)
    {
        if (null !== $this->colltwSubscriptionStatusI18ns && !$overrideExisting) {
            return;
        }
        $this->colltwSubscriptionStatusI18ns = new PropelObjectCollection();
        $this->colltwSubscriptionStatusI18ns->setModel('twSubscriptionStatusI18n');
    }

    /**
     * Gets an array of twSubscriptionStatusI18n objects which contain a foreign key that references this object.
     *
     * If the $criteria is not null, it is used to always fetch the results from the database.
     * Otherwise the results are fetched from the database the first time, then cached.
     * Next time the same method is called without $criteria, the cached collection is returned.
     * If this twSubscriptionStatus is new, it will return
     * an empty collection or the current collection; the criteria is ignored on a new object.
     *
     * @param      Criteria $criteria optional Criteria object to narrow the query
     * @param      PropelPDO $con optional connection object
     * @return PropelObjectCollection|twSubscriptionStatusI18n[] List of twSubscriptionStatusI18n objects
     * @throws PropelException
     */
    public function gettwSubscriptionStatusI18ns($criteria = null, PropelPDO $con = null)
    {
        if (null === $this->colltwSubscriptionStatusI18ns || null !== $criteria) {
            if ($this->isNew() && null === $this->colltwSubscriptionStatusI18ns) {
                // return empty collection
                $this->inittwSubscriptionStatusI18ns();
            } else {
                $colltwSubscriptionStatusI18ns = twSubscriptionStatusI18nQuery::create(null, $criteria)
                    ->filterBytwSubscriptionStatus($this)
                    ->find($con);
                if (null !== $criteria) {
                    return $colltwSubscriptionStatusI18ns;
                }
                $this->colltwSubscriptionStatusI18ns = $colltwSubscriptionStatusI18ns;
            }
        }

        return $this->colltwSubscriptionStatusI18ns;
    }

    /**
     * Sets a collection of twSubscriptionStatusI18n objects related by a one-to-many relationship
     * to the current object.
     * It will also schedule objects for deletion based on a diff between old objects (aka persisted)
     * and new objects from the given Propel collection.
     *
     * @param      PropelCollection $twSubscriptionStatusI18ns A Propel collection.
     * @param      PropelPDO $con Optional connection object
     */
    public function settwSubscriptionStatusI18ns(PropelCollection $twSubscriptionStatusI18ns, PropelPDO $con = null)
    {
        $this->twSubscriptionStatusI18nsScheduledForDeletion = $this->gettwSubscriptionStatusI18ns(new Criteria(), $con)->diff($twSubscriptionStatusI18ns);

        foreach ($this->twSubscriptionStatusI18nsScheduledForDeletion as $twSubscriptionStatusI18nRemoved) {
            $twSubscriptionStatusI18nRemoved->settwSubscriptionStatus(null);
        }

        $this->colltwSubscriptionStatusI18ns = null;
        foreach ($twSubscriptionStatusI18ns as $twSubscriptionStatusI18n) {
            $this->addtwSubscriptionStatusI18n($twSubscriptionStatusI18n);
        }

        $this->colltwSubscriptionStatusI18ns = $twSubscriptionStatusI18ns;
    }

    /**
     * Returns the number of related twSubscriptionStatusI18n objects.
     *
     * @param      Criteria $criteria
     * @param      boolean $distinct
     * @param      PropelPDO $con
     * @return int             Count of related twSubscriptionStatusI18n objects.
     * @throws PropelException
     */
    public function counttwSubscriptionStatusI18ns(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
    {
        if (null === $this->colltwSubscriptionStatusI18ns || null !== $criteria) {
            if ($this->isNew() && null === $this->colltwSubscriptionStatusI18ns) {
                return 0;
            } else {
                $query = twSubscriptionStatusI18nQuery::create(null, $criteria);
                if ($distinct) {
                    $query->distinct();
                }

                return $query
                    ->filterBytwSubscriptionStatus($this)
                    ->count($con);
            }
        } else {
            return count($this->colltwSubscriptionStatusI18ns);
        }
    }

    /**
     * Method called to associate a twSubscriptionStatusI18n object to this object
     * through the twSubscriptionStatusI18n foreign key attribute.
     *
     * @param    twSubscriptionStatusI18n $l twSubscriptionStatusI18n
     * @return   twSubscriptionStatus The current object (for fluent API support)
     */
    public function addtwSubscriptionStatusI18n(twSubscriptionStatusI18n $l)
    {
        if ($this->colltwSubscriptionStatusI18ns === null) {
            $this->inittwSubscriptionStatusI18ns();
        }
        if (!$this->colltwSubscriptionStatusI18ns->contains($l)) { // only add it if the **same** object is not already associated
            $this->doAddtwSubscriptionStatusI18n($l);
        }

        return $this;
    }

    /**
     * @param	twSubscriptionStatusI18n $twSubscriptionStatusI18n The twSubscriptionStatusI18n object to add.
     */
    protected function doAddtwSubscriptionStatusI18n($twSubscriptionStatusI18n)
    {
        $this->colltwSubscriptionStatusI18ns[]= $twSubscriptionStatusI18n;
        $twSubscriptionStatusI18n->settwSubscriptionStatus($this);
    }

    /**
     * @param	twSubscriptionStatusI18n $twSubscriptionStatusI18n The twSubscriptionStatusI18n object to remove.
     */
    public function removetwSubscriptionStatusI18n($twSubscriptionStatusI18n)
    {
        if ($this->gettwSubscriptionStatusI18ns()->contains($twSubscriptionStatusI18n)) {
            $this->colltwSubscriptionStatusI18ns->remove($this->colltwSubscriptionStatusI18ns->search($twSubscriptionStatusI18n));
            if (null === $this->twSubscriptionStatusI18nsScheduledForDeletion) {
                $this->twSubscriptionStatusI18nsScheduledForDeletion = clone $this->colltwSubscriptionStatusI18ns;
                $this->twSubscriptionStatusI18nsScheduledForDeletion->clear();
            }
            $this->twSubscriptionStatusI18nsScheduledForDeletion[]= $twSubscriptionStatusI18n;
            $twSubscriptionStatusI18n->settwSubscriptionStatus(null);
        }
    }

    /**
     * Clears out the colltwSubscriptionEmails collection
     *
     * This does not modify the database; however, it will remove any associated objects, causing
     * them to be refetched by subsequent calls to accessor method.
     *
     * @return void
     * @see        addtwSubscriptionEmails()
     */
    public function cleartwSubscriptionEmails()
    {
        $this->colltwSubscriptionEmails = null; // important to set this to NULL since that means it is uninitialized
    }

    /**
     * Initializes the colltwSubscriptionEmails collection.
     *
     * By default this just sets the colltwSubscriptionEmails collection to an empty array (like clearcolltwSubscriptionEmails());
     * however, you may wish to override this method in your stub class to provide setting appropriate
     * to your application -- for example, setting the initial array to the values stored in database.
     *
     * @param      boolean $overrideExisting If set to true, the method call initializes
     *                                        the collection even if it is not empty
     *
     * @return void
     */
    public function inittwSubscriptionEmails($overrideExisting = true)
    {
        if (null !== $this->colltwSubscriptionEmails && !$overrideExisting) {
            return;
        }
        $this->colltwSubscriptionEmails = new PropelObjectCollection();
        $this->colltwSubscriptionEmails->setModel('twSubscriptionEmail');
    }

    /**
     * Gets an array of twSubscriptionEmail objects which contain a foreign key that references this object.
     *
     * If the $criteria is not null, it is used to always fetch the results from the database.
     * Otherwise the results are fetched from the database the first time, then cached.
     * Next time the same method is called without $criteria, the cached collection is returned.
     * If this twSubscriptionStatus is new, it will return
     * an empty collection or the current collection; the criteria is ignored on a new object.
     *
     * @param      Criteria $criteria optional Criteria object to narrow the query
     * @param      PropelPDO $con optional connection object
     * @return PropelObjectCollection|twSubscriptionEmail[] List of twSubscriptionEmail objects
     * @throws PropelException
     */
    public function gettwSubscriptionEmails($criteria = null, PropelPDO $con = null)
    {
        if (null === $this->colltwSubscriptionEmails || null !== $criteria) {
            if ($this->isNew() && null === $this->colltwSubscriptionEmails) {
                // return empty collection
                $this->inittwSubscriptionEmails();
            } else {
                $colltwSubscriptionEmails = twSubscriptionEmailQuery::create(null, $criteria)
                    ->filterBytwSubscriptionStatus($this)
                    ->find($con);
                if (null !== $criteria) {
                    return $colltwSubscriptionEmails;
                }
                $this->colltwSubscriptionEmails = $colltwSubscriptionEmails;
            }
        }

        return $this->colltwSubscriptionEmails;
    }

    /**
     * Sets a collection of twSubscriptionEmail objects related by a one-to-many relationship
     * to the current object.
     * It will also schedule objects for deletion based on a diff between old objects (aka persisted)
     * and new objects from the given Propel collection.
     *
     * @param      PropelCollection $twSubscriptionEmails A Propel collection.
     * @param      PropelPDO $con Optional connection object
     */
    public function settwSubscriptionEmails(PropelCollection $twSubscriptionEmails, PropelPDO $con = null)
    {
        $this->twSubscriptionEmailsScheduledForDeletion = $this->gettwSubscriptionEmails(new Criteria(), $con)->diff($twSubscriptionEmails);

        foreach ($this->twSubscriptionEmailsScheduledForDeletion as $twSubscriptionEmailRemoved) {
            $twSubscriptionEmailRemoved->settwSubscriptionStatus(null);
        }

        $this->colltwSubscriptionEmails = null;
        foreach ($twSubscriptionEmails as $twSubscriptionEmail) {
            $this->addtwSubscriptionEmail($twSubscriptionEmail);
        }

        $this->colltwSubscriptionEmails = $twSubscriptionEmails;
    }

    /**
     * Returns the number of related twSubscriptionEmail objects.
     *
     * @param      Criteria $criteria
     * @param      boolean $distinct
     * @param      PropelPDO $con
     * @return int             Count of related twSubscriptionEmail objects.
     * @throws PropelException
     */
    public function counttwSubscriptionEmails(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
    {
        if (null === $this->colltwSubscriptionEmails || null !== $criteria) {
            if ($this->isNew() && null === $this->colltwSubscriptionEmails) {
                return 0;
            } else {
                $query = twSubscriptionEmailQuery::create(null, $criteria);
                if ($distinct) {
                    $query->distinct();
                }

                return $query
                    ->filterBytwSubscriptionStatus($this)
                    ->count($con);
            }
        } else {
            return count($this->colltwSubscriptionEmails);
        }
    }

    /**
     * Method called to associate a twSubscriptionEmail object to this object
     * through the twSubscriptionEmail foreign key attribute.
     *
     * @param    twSubscriptionEmail $l twSubscriptionEmail
     * @return   twSubscriptionStatus The current object (for fluent API support)
     */
    public function addtwSubscriptionEmail(twSubscriptionEmail $l)
    {
        if ($this->colltwSubscriptionEmails === null) {
            $this->inittwSubscriptionEmails();
        }
        if (!$this->colltwSubscriptionEmails->contains($l)) { // only add it if the **same** object is not already associated
            $this->doAddtwSubscriptionEmail($l);
        }

        return $this;
    }

    /**
     * @param	twSubscriptionEmail $twSubscriptionEmail The twSubscriptionEmail object to add.
     */
    protected function doAddtwSubscriptionEmail($twSubscriptionEmail)
    {
        $this->colltwSubscriptionEmails[]= $twSubscriptionEmail;
        $twSubscriptionEmail->settwSubscriptionStatus($this);
    }

    /**
     * @param	twSubscriptionEmail $twSubscriptionEmail The twSubscriptionEmail object to remove.
     */
    public function removetwSubscriptionEmail($twSubscriptionEmail)
    {
        if ($this->gettwSubscriptionEmails()->contains($twSubscriptionEmail)) {
            $this->colltwSubscriptionEmails->remove($this->colltwSubscriptionEmails->search($twSubscriptionEmail));
            if (null === $this->twSubscriptionEmailsScheduledForDeletion) {
                $this->twSubscriptionEmailsScheduledForDeletion = clone $this->colltwSubscriptionEmails;
                $this->twSubscriptionEmailsScheduledForDeletion->clear();
            }
            $this->twSubscriptionEmailsScheduledForDeletion[]= $twSubscriptionEmail;
            $twSubscriptionEmail->settwSubscriptionStatus(null);
        }
    }


    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this twSubscriptionStatus is new, it will return
     * an empty collection; or if this twSubscriptionStatus has previously
     * been saved, it will retrieve related twSubscriptionEmails from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in twSubscriptionStatus.
     *
     * @param      Criteria $criteria optional Criteria object to narrow the query
     * @param      PropelPDO $con optional connection object
     * @param      string $join_behavior optional join type to use (defaults to Criteria::LEFT_JOIN)
     * @return PropelObjectCollection|twSubscriptionEmail[] List of twSubscriptionEmail objects
     */
    public function gettwSubscriptionEmailsJointwSubscriptionList($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
    {
        $query = twSubscriptionEmailQuery::create(null, $criteria);
        $query->joinWith('twSubscriptionList', $join_behavior);

        return $this->gettwSubscriptionEmails($query, $con);
    }

    /**
     * Clears the current object and sets all attributes to their default values
     */
    public function clear()
    {
        $this->id = null;
        $this->code = null;
        $this->alreadyInSave = false;
        $this->alreadyInValidation = false;
        $this->clearAllReferences();
        $this->resetModified();
        $this->setNew(true);
        $this->setDeleted(false);
    }

    /**
     * Resets all references to other model objects or collections of model objects.
     *
     * This method is a user-space workaround for PHP's inability to garbage collect
     * objects with circular references (even in PHP 5.3). This is currently necessary
     * when using Propel in certain daemon or large-volumne/high-memory operations.
     *
     * @param      boolean $deep Whether to also clear the references on all referrer objects.
     */
    public function clearAllReferences($deep = false)
    {
        if ($deep) {
            if ($this->colltwSubscriptionStatusI18ns) {
                foreach ($this->colltwSubscriptionStatusI18ns as $o) {
                    $o->clearAllReferences($deep);
                }
            }
            if ($this->colltwSubscriptionEmails) {
                foreach ($this->colltwSubscriptionEmails as $o) {
                    $o->clearAllReferences($deep);
                }
            }
        } // if ($deep)

        if ($this->colltwSubscriptionStatusI18ns instanceof PropelCollection) {
            $this->colltwSubscriptionStatusI18ns->clearIterator();
        }
        $this->colltwSubscriptionStatusI18ns = null;
        if ($this->colltwSubscriptionEmails instanceof PropelCollection) {
            $this->colltwSubscriptionEmails->clearIterator();
        }
        $this->colltwSubscriptionEmails = null;
    }

    /**
     * Return the string representation of this object
     *
     * @return string
     */
    public function __toString()
    {
        return (string) $this->exportTo(twSubscriptionStatusPeer::DEFAULT_STRING_FORMAT);
    }

	// symfony_i18n behavior
	
	/**
	 * Returns the culture.
	 *
	 * @return string The culture
	 */
	public function getCulture()
	{
	  return $this->culture;
	}
	
	/**
	 * Sets the culture.
	 *
	 * @param string  The culture to set
	 *
	 * @return twSubscriptionStatus
	 */
	public function setCulture($culture)
	{
	  $this->culture = $culture;
	  return $this;
	}
	
	/**
	 * Returns the "name" value from the current {@link twSubscriptionStatusI18n}.
	 */
	public function getName($culture = null)
	{
	  return $this->getCurrenttwSubscriptionStatusI18n($culture)->getName();
	}
	
	/**
	 * Sets the "name" value of the current {@link twSubscriptionStatusI18n}.
	 *
	 * @return twSubscriptionStatus
	 */
	public function setName($value, $culture = null)
	{
	  $this->getCurrenttwSubscriptionStatusI18n($culture)->setName($value);
	  return $this;
	}
	
	/**
	 * Returns the current translation.
	 *
	 * @return twSubscriptionStatusI18n
	 */
	public function getCurrenttwSubscriptionStatusI18n($culture = null)
	{
	  if (null === $culture)
	  {
	    $culture = null === $this->culture ? sfPropel::getDefaultCulture() : $this->culture;
	  }
	
	  if (!isset($this->current_i18n[$culture]))
	  {
	    $object = $this->isNew() ? null : twSubscriptionStatusI18nPeer::retrieveByPK($this->getPrimaryKey(), $culture);
	    if ($object)
	    {
	      $this->settwSubscriptionStatusI18nForCulture($object, $culture);
	    }
	    else
	    {
	      $this->settwSubscriptionStatusI18nForCulture(new twSubscriptionStatusI18n(), $culture);
	      $this->current_i18n[$culture]->setCulture($culture);
	    }
	  }
	
	  return $this->current_i18n[$culture];
	}
	
	/**
	 * Sets the translation object for a culture.
	 */
	public function settwSubscriptionStatusI18nForCulture(twSubscriptionStatusI18n $object, $culture)
	{
	  $this->current_i18n[$culture] = $object;
	  $this->addtwSubscriptionStatusI18n($object);
	}

    /**
     * Catches calls to virtual methods
     */
    public function __call($name, $params)
    {
        
		// symfony_behaviors behavior
		if ($callable = sfMixer::getCallable('BasetwSubscriptionStatus:' . $name))
		{
		  array_unshift($params, $this);
		  return call_user_func_array($callable, $params);
		}


        return parent::__call($name, $params);
    }

} // BasetwSubscriptionStatus
