<?php


/**
 * Base class that represents a query for the 'tw_subscription_status_i18n' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.6 on:
 *
 * Thu Sep 27 23:40:08 2012
 *
 * @method     twSubscriptionStatusI18nQuery orderById($order = Criteria::ASC) Order by the id column
 * @method     twSubscriptionStatusI18nQuery orderByName($order = Criteria::ASC) Order by the name column
 * @method     twSubscriptionStatusI18nQuery orderByCulture($order = Criteria::ASC) Order by the culture column
 *
 * @method     twSubscriptionStatusI18nQuery groupById() Group by the id column
 * @method     twSubscriptionStatusI18nQuery groupByName() Group by the name column
 * @method     twSubscriptionStatusI18nQuery groupByCulture() Group by the culture column
 *
 * @method     twSubscriptionStatusI18nQuery leftJoin($relation) Adds a LEFT JOIN clause to the query
 * @method     twSubscriptionStatusI18nQuery rightJoin($relation) Adds a RIGHT JOIN clause to the query
 * @method     twSubscriptionStatusI18nQuery innerJoin($relation) Adds a INNER JOIN clause to the query
 *
 * @method     twSubscriptionStatusI18nQuery leftJointwSubscriptionStatus($relationAlias = null) Adds a LEFT JOIN clause to the query using the twSubscriptionStatus relation
 * @method     twSubscriptionStatusI18nQuery rightJointwSubscriptionStatus($relationAlias = null) Adds a RIGHT JOIN clause to the query using the twSubscriptionStatus relation
 * @method     twSubscriptionStatusI18nQuery innerJointwSubscriptionStatus($relationAlias = null) Adds a INNER JOIN clause to the query using the twSubscriptionStatus relation
 *
 * @method     twSubscriptionStatusI18n findOne(PropelPDO $con = null) Return the first twSubscriptionStatusI18n matching the query
 * @method     twSubscriptionStatusI18n findOneOrCreate(PropelPDO $con = null) Return the first twSubscriptionStatusI18n matching the query, or a new twSubscriptionStatusI18n object populated from the query conditions when no match is found
 *
 * @method     twSubscriptionStatusI18n findOneById(int $id) Return the first twSubscriptionStatusI18n filtered by the id column
 * @method     twSubscriptionStatusI18n findOneByName(string $name) Return the first twSubscriptionStatusI18n filtered by the name column
 * @method     twSubscriptionStatusI18n findOneByCulture(string $culture) Return the first twSubscriptionStatusI18n filtered by the culture column
 *
 * @method     array findById(int $id) Return twSubscriptionStatusI18n objects filtered by the id column
 * @method     array findByName(string $name) Return twSubscriptionStatusI18n objects filtered by the name column
 * @method     array findByCulture(string $culture) Return twSubscriptionStatusI18n objects filtered by the culture column
 *
 * @package    propel.generator.plugins.twSubscriptionPlugin.lib.model.om
 */
abstract class BasetwSubscriptionStatusI18nQuery extends ModelCriteria
{
    
    /**
     * Initializes internal state of BasetwSubscriptionStatusI18nQuery object.
     *
     * @param     string $dbName The dabase name
     * @param     string $modelName The phpName of a model, e.g. 'Book'
     * @param     string $modelAlias The alias for the model in this query, e.g. 'b'
     */
    public function __construct($dbName = 'propel', $modelName = 'twSubscriptionStatusI18n', $modelAlias = null)
    {
        parent::__construct($dbName, $modelName, $modelAlias);
    }

    /**
     * Returns a new twSubscriptionStatusI18nQuery object.
     *
     * @param     string $modelAlias The alias of a model in the query
     * @param     twSubscriptionStatusI18nQuery|Criteria $criteria Optional Criteria to build the query from
     *
     * @return twSubscriptionStatusI18nQuery
     */
    public static function create($modelAlias = null, $criteria = null)
    {
        if ($criteria instanceof twSubscriptionStatusI18nQuery) {
            return $criteria;
        }
        $query = new twSubscriptionStatusI18nQuery();
        if (null !== $modelAlias) {
            $query->setModelAlias($modelAlias);
        }
        if ($criteria instanceof Criteria) {
            $query->mergeWith($criteria);
        }

        return $query;
    }

    /**
     * Find object by primary key.
     * Propel uses the instance pool to skip the database if the object exists.
     * Go fast if the query is untouched.
     *
     * <code>
     * $obj = $c->findPk(array(12, 34), $con);
     * </code>
     *
     * @param array $key Primary key to use for the query 
                         A Primary key composition: [$id, $culture]
     * @param     PropelPDO $con an optional connection object
     *
     * @return   twSubscriptionStatusI18n|twSubscriptionStatusI18n[]|mixed the result, formatted by the current formatter
     */
    public function findPk($key, $con = null)
    {
        if ($key === null) {
            return null;
        }
        if ((null !== ($obj = twSubscriptionStatusI18nPeer::getInstanceFromPool(serialize(array((string) $key[0], (string) $key[1]))))) && !$this->formatter) {
            // the object is alredy in the instance pool
            return $obj;
        }
        if ($con === null) {
            $con = Propel::getConnection(twSubscriptionStatusI18nPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }
        $this->basePreSelect($con);
        if ($this->formatter || $this->modelAlias || $this->with || $this->select
         || $this->selectColumns || $this->asColumns || $this->selectModifiers
         || $this->map || $this->having || $this->joins) {
            return $this->findPkComplex($key, $con);
        } else {
            return $this->findPkSimple($key, $con);
        }
    }

    /**
     * Find object by primary key using raw SQL to go fast.
     * Bypass doSelect() and the object formatter by using generated code.
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return   twSubscriptionStatusI18n A model object, or null if the key is not found
     * @throws   PropelException
     */
    protected function findPkSimple($key, $con)
    {
        $sql = 'SELECT `ID`, `NAME`, `CULTURE` FROM `tw_subscription_status_i18n` WHERE `ID` = :p0 AND `CULTURE` = :p1';
        try {
            $stmt = $con->prepare($sql);
			$stmt->bindValue(':p0', $key[0], PDO::PARAM_INT);
			$stmt->bindValue(':p1', $key[1], PDO::PARAM_STR);
            $stmt->execute();
        } catch (Exception $e) {
            Propel::log($e->getMessage(), Propel::LOG_ERR);
            throw new PropelException(sprintf('Unable to execute SELECT statement [%s]', $sql), $e);
        }
        $obj = null;
        if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
            $obj = new twSubscriptionStatusI18n();
            $obj->hydrate($row);
            twSubscriptionStatusI18nPeer::addInstanceToPool($obj, serialize(array((string) $key[0], (string) $key[1])));
        }
        $stmt->closeCursor();

        return $obj;
    }

    /**
     * Find object by primary key.
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return twSubscriptionStatusI18n|twSubscriptionStatusI18n[]|mixed the result, formatted by the current formatter
     */
    protected function findPkComplex($key, $con)
    {
        // As the query uses a PK condition, no limit(1) is necessary.
        $criteria = $this->isKeepQuery() ? clone $this : $this;
        $stmt = $criteria
            ->filterByPrimaryKey($key)
            ->doSelect($con);

        return $criteria->getFormatter()->init($criteria)->formatOne($stmt);
    }

    /**
     * Find objects by primary key
     * <code>
     * $objs = $c->findPks(array(array(12, 56), array(832, 123), array(123, 456)), $con);
     * </code>
     * @param     array $keys Primary keys to use for the query
     * @param     PropelPDO $con an optional connection object
     *
     * @return PropelObjectCollection|twSubscriptionStatusI18n[]|mixed the list of results, formatted by the current formatter
     */
    public function findPks($keys, $con = null)
    {
        if ($con === null) {
            $con = Propel::getConnection($this->getDbName(), Propel::CONNECTION_READ);
        }
        $this->basePreSelect($con);
        $criteria = $this->isKeepQuery() ? clone $this : $this;
        $stmt = $criteria
            ->filterByPrimaryKeys($keys)
            ->doSelect($con);

        return $criteria->getFormatter()->init($criteria)->format($stmt);
    }

    /**
     * Filter the query by primary key
     *
     * @param     mixed $key Primary key to use for the query
     *
     * @return twSubscriptionStatusI18nQuery The current query, for fluid interface
     */
    public function filterByPrimaryKey($key)
    {
        $this->addUsingAlias(twSubscriptionStatusI18nPeer::ID, $key[0], Criteria::EQUAL);
        $this->addUsingAlias(twSubscriptionStatusI18nPeer::CULTURE, $key[1], Criteria::EQUAL);

        return $this;
    }

    /**
     * Filter the query by a list of primary keys
     *
     * @param     array $keys The list of primary key to use for the query
     *
     * @return twSubscriptionStatusI18nQuery The current query, for fluid interface
     */
    public function filterByPrimaryKeys($keys)
    {
        if (empty($keys)) {
            return $this->add(null, '1<>1', Criteria::CUSTOM);
        }
        foreach ($keys as $key) {
            $cton0 = $this->getNewCriterion(twSubscriptionStatusI18nPeer::ID, $key[0], Criteria::EQUAL);
            $cton1 = $this->getNewCriterion(twSubscriptionStatusI18nPeer::CULTURE, $key[1], Criteria::EQUAL);
            $cton0->addAnd($cton1);
            $this->addOr($cton0);
        }

        return $this;
    }

    /**
     * Filter the query on the id column
     *
     * Example usage:
     * <code>
     * $query->filterById(1234); // WHERE id = 1234
     * $query->filterById(array(12, 34)); // WHERE id IN (12, 34)
     * $query->filterById(array('min' => 12)); // WHERE id > 12
     * </code>
     *
     * @see       filterBytwSubscriptionStatus()
     *
     * @param     mixed $id The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return twSubscriptionStatusI18nQuery The current query, for fluid interface
     */
    public function filterById($id = null, $comparison = null)
    {
        if (is_array($id) && null === $comparison) {
            $comparison = Criteria::IN;
        }

        return $this->addUsingAlias(twSubscriptionStatusI18nPeer::ID, $id, $comparison);
    }

    /**
     * Filter the query on the name column
     *
     * Example usage:
     * <code>
     * $query->filterByName('fooValue');   // WHERE name = 'fooValue'
     * $query->filterByName('%fooValue%'); // WHERE name LIKE '%fooValue%'
     * </code>
     *
     * @param     string $name The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return twSubscriptionStatusI18nQuery The current query, for fluid interface
     */
    public function filterByName($name = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($name)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $name)) {
                $name = str_replace('*', '%', $name);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(twSubscriptionStatusI18nPeer::NAME, $name, $comparison);
    }

    /**
     * Filter the query on the culture column
     *
     * Example usage:
     * <code>
     * $query->filterByCulture('fooValue');   // WHERE culture = 'fooValue'
     * $query->filterByCulture('%fooValue%'); // WHERE culture LIKE '%fooValue%'
     * </code>
     *
     * @param     string $culture The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return twSubscriptionStatusI18nQuery The current query, for fluid interface
     */
    public function filterByCulture($culture = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($culture)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $culture)) {
                $culture = str_replace('*', '%', $culture);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(twSubscriptionStatusI18nPeer::CULTURE, $culture, $comparison);
    }

    /**
     * Filter the query by a related twSubscriptionStatus object
     *
     * @param   twSubscriptionStatus|PropelObjectCollection $twSubscriptionStatus The related object(s) to use as filter
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return   twSubscriptionStatusI18nQuery The current query, for fluid interface
     * @throws   PropelException - if the provided filter is invalid.
     */
    public function filterBytwSubscriptionStatus($twSubscriptionStatus, $comparison = null)
    {
        if ($twSubscriptionStatus instanceof twSubscriptionStatus) {
            return $this
                ->addUsingAlias(twSubscriptionStatusI18nPeer::ID, $twSubscriptionStatus->getId(), $comparison);
        } elseif ($twSubscriptionStatus instanceof PropelObjectCollection) {
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }

            return $this
                ->addUsingAlias(twSubscriptionStatusI18nPeer::ID, $twSubscriptionStatus->toKeyValue('PrimaryKey', 'Id'), $comparison);
        } else {
            throw new PropelException('filterBytwSubscriptionStatus() only accepts arguments of type twSubscriptionStatus or PropelCollection');
        }
    }

    /**
     * Adds a JOIN clause to the query using the twSubscriptionStatus relation
     *
     * @param     string $relationAlias optional alias for the relation
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return twSubscriptionStatusI18nQuery The current query, for fluid interface
     */
    public function jointwSubscriptionStatus($relationAlias = null, $joinType = Criteria::INNER_JOIN)
    {
        $tableMap = $this->getTableMap();
        $relationMap = $tableMap->getRelation('twSubscriptionStatus');

        // create a ModelJoin object for this join
        $join = new ModelJoin();
        $join->setJoinType($joinType);
        $join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
        if ($previousJoin = $this->getPreviousJoin()) {
            $join->setPreviousJoin($previousJoin);
        }

        // add the ModelJoin to the current object
        if ($relationAlias) {
            $this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
            $this->addJoinObject($join, $relationAlias);
        } else {
            $this->addJoinObject($join, 'twSubscriptionStatus');
        }

        return $this;
    }

    /**
     * Use the twSubscriptionStatus relation twSubscriptionStatus object
     *
     * @see       useQuery()
     *
     * @param     string $relationAlias optional alias for the relation,
     *                                   to be used as main alias in the secondary query
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return   twSubscriptionStatusQuery A secondary query class using the current class as primary query
     */
    public function usetwSubscriptionStatusQuery($relationAlias = null, $joinType = Criteria::INNER_JOIN)
    {
        return $this
            ->jointwSubscriptionStatus($relationAlias, $joinType)
            ->useQuery($relationAlias ? $relationAlias : 'twSubscriptionStatus', 'twSubscriptionStatusQuery');
    }

    /**
     * Exclude object from result
     *
     * @param   twSubscriptionStatusI18n $twSubscriptionStatusI18n Object to remove from the list of results
     *
     * @return twSubscriptionStatusI18nQuery The current query, for fluid interface
     */
    public function prune($twSubscriptionStatusI18n = null)
    {
        if ($twSubscriptionStatusI18n) {
            $this->addCond('pruneCond0', $this->getAliasedColName(twSubscriptionStatusI18nPeer::ID), $twSubscriptionStatusI18n->getId(), Criteria::NOT_EQUAL);
            $this->addCond('pruneCond1', $this->getAliasedColName(twSubscriptionStatusI18nPeer::CULTURE), $twSubscriptionStatusI18n->getCulture(), Criteria::NOT_EQUAL);
            $this->combine(array('pruneCond0', 'pruneCond1'), Criteria::LOGICAL_OR);
        }

        return $this;
    }

} // BasetwSubscriptionStatusI18nQuery