<?php


/**
 * Base class that represents a row from the 'tw_subscription_message_type' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.6 on:
 *
 * Thu Sep 27 23:40:08 2012
 *
 * @package    propel.generator.plugins.twSubscriptionPlugin.lib.model.om
 */
abstract class BasetwSubscriptionMessageType extends BaseObject 
{

    /**
     * Peer class name
     */
    const PEER = 'twSubscriptionMessageTypePeer';

    /**
     * The Peer class.
     * Instance provides a convenient way of calling static methods on a class
     * that calling code may not be able to identify.
     * @var        twSubscriptionMessageTypePeer
     */
    protected static $peer;

    /**
     * The flag var to prevent infinit loop in deep copy
     * @var       boolean
     */
    protected $startCopy = false;

    /**
     * The value for the id field.
     * @var        int
     */
    protected $id;

    /**
     * The value for the code field.
     * @var        string
     */
    protected $code;

    /**
     * @var        PropelObjectCollection|twSubscriptionMessageTypeI18n[] Collection to store aggregation of twSubscriptionMessageTypeI18n objects.
     */
    protected $colltwSubscriptionMessageTypeI18ns;

    /**
     * @var        PropelObjectCollection|twSubscriptionTemplate[] Collection to store aggregation of twSubscriptionTemplate objects.
     */
    protected $colltwSubscriptionTemplates;

    /**
     * @var        PropelObjectCollection|twSubscriptionMessage[] Collection to store aggregation of twSubscriptionMessage objects.
     */
    protected $colltwSubscriptionMessages;

    /**
     * @var        PropelObjectCollection|twSubscriptionListInvitation[] Collection to store aggregation of twSubscriptionListInvitation objects.
     */
    protected $colltwSubscriptionListInvitations;

    /**
     * @var        PropelObjectCollection|twSubscriptionMailQueue[] Collection to store aggregation of twSubscriptionMailQueue objects.
     */
    protected $colltwSubscriptionMailQueues;

    /**
     * Flag to prevent endless save loop, if this object is referenced
     * by another object which falls in this transaction.
     * @var        boolean
     */
    protected $alreadyInSave = false;

    /**
     * Flag to prevent endless validation loop, if this object is referenced
     * by another object which falls in this transaction.
     * @var        boolean
     */
    protected $alreadyInValidation = false;

	// symfony_i18n behavior
	
	/**
	 * @var string The value for the culture field
	 */
	protected $culture = null;
	
	/**
	 * @var array Current I18N objects
	 */
	protected $current_i18n = array();

    /**
     * An array of objects scheduled for deletion.
     * @var		PropelObjectCollection
     */
    protected $twSubscriptionMessageTypeI18nsScheduledForDeletion = null;

    /**
     * An array of objects scheduled for deletion.
     * @var		PropelObjectCollection
     */
    protected $twSubscriptionTemplatesScheduledForDeletion = null;

    /**
     * An array of objects scheduled for deletion.
     * @var		PropelObjectCollection
     */
    protected $twSubscriptionMessagesScheduledForDeletion = null;

    /**
     * An array of objects scheduled for deletion.
     * @var		PropelObjectCollection
     */
    protected $twSubscriptionListInvitationsScheduledForDeletion = null;

    /**
     * An array of objects scheduled for deletion.
     * @var		PropelObjectCollection
     */
    protected $twSubscriptionMailQueuesScheduledForDeletion = null;

    /**
     * Get the [id] column value.
     * 
     * @return   int
     */
    public function getId()
    {

        return $this->id;
    }

    /**
     * Get the [code] column value.
     * 
     * @return   string
     */
    public function getCode()
    {

        return $this->code;
    }

    /**
     * Set the value of [id] column.
     * 
     * @param      int $v new value
     * @return   twSubscriptionMessageType The current object (for fluent API support)
     */
    public function setId($v)
    {
        if ($v !== null) {
            $v = (int) $v;
        }

        if ($this->id !== $v) {
            $this->id = $v;
            $this->modifiedColumns[] = twSubscriptionMessageTypePeer::ID;
        }


        return $this;
    } // setId()

    /**
     * Set the value of [code] column.
     * 
     * @param      string $v new value
     * @return   twSubscriptionMessageType The current object (for fluent API support)
     */
    public function setCode($v)
    {
        if ($v !== null) {
            $v = (string) $v;
        }

        if ($this->code !== $v) {
            $this->code = $v;
            $this->modifiedColumns[] = twSubscriptionMessageTypePeer::CODE;
        }


        return $this;
    } // setCode()

    /**
     * Indicates whether the columns in this object are only set to default values.
     *
     * This method can be used in conjunction with isModified() to indicate whether an object is both
     * modified _and_ has some values set which are non-default.
     *
     * @return boolean Whether the columns in this object are only been set with default values.
     */
    public function hasOnlyDefaultValues()
    {
        // otherwise, everything was equal, so return TRUE
        return true;
    } // hasOnlyDefaultValues()

    /**
     * Hydrates (populates) the object variables with values from the database resultset.
     *
     * An offset (0-based "start column") is specified so that objects can be hydrated
     * with a subset of the columns in the resultset rows.  This is needed, for example,
     * for results of JOIN queries where the resultset row includes columns from two or
     * more tables.
     *
     * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
     * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
     * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
     * @return int             next starting column
     * @throws PropelException - Any caught Exception will be rewrapped as a PropelException.
     */
    public function hydrate($row, $startcol = 0, $rehydrate = false)
    {
        try {

            $this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
            $this->code = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
            $this->resetModified();

            $this->setNew(false);

            if ($rehydrate) {
                $this->ensureConsistency();
            }

            return $startcol + 2; // 2 = twSubscriptionMessageTypePeer::NUM_HYDRATE_COLUMNS.

        } catch (Exception $e) {
            throw new PropelException("Error populating twSubscriptionMessageType object", $e);
        }
    }

    /**
     * Checks and repairs the internal consistency of the object.
     *
     * This method is executed after an already-instantiated object is re-hydrated
     * from the database.  It exists to check any foreign keys to make sure that
     * the objects related to the current object are correct based on foreign key.
     *
     * You can override this method in the stub class, but you should always invoke
     * the base method from the overridden method (i.e. parent::ensureConsistency()),
     * in case your model changes.
     *
     * @throws PropelException
     */
    public function ensureConsistency()
    {

    } // ensureConsistency

    /**
     * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
     *
     * This will only work if the object has been saved and has a valid primary key set.
     *
     * @param      boolean $deep (optional) Whether to also de-associated any related objects.
     * @param      PropelPDO $con (optional) The PropelPDO connection to use.
     * @return void
     * @throws PropelException - if this object is deleted, unsaved or doesn't have pk match in db
     */
    public function reload($deep = false, PropelPDO $con = null)
    {
        if ($this->isDeleted()) {
            throw new PropelException("Cannot reload a deleted object.");
        }

        if ($this->isNew()) {
            throw new PropelException("Cannot reload an unsaved object.");
        }

        if ($con === null) {
            $con = Propel::getConnection(twSubscriptionMessageTypePeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }

        // We don't need to alter the object instance pool; we're just modifying this instance
        // already in the pool.

        $stmt = twSubscriptionMessageTypePeer::doSelectStmt($this->buildPkeyCriteria(), $con);
        $row = $stmt->fetch(PDO::FETCH_NUM);
        $stmt->closeCursor();
        if (!$row) {
            throw new PropelException('Cannot find matching row in the database to reload object values.');
        }
        $this->hydrate($row, 0, true); // rehydrate

        if ($deep) {  // also de-associate any related objects?

            $this->colltwSubscriptionMessageTypeI18ns = null;

            $this->colltwSubscriptionTemplates = null;

            $this->colltwSubscriptionMessages = null;

            $this->colltwSubscriptionListInvitations = null;

            $this->colltwSubscriptionMailQueues = null;

        } // if (deep)
    }

    /**
     * Removes this object from datastore and sets delete attribute.
     *
     * @param      PropelPDO $con
     * @return void
     * @throws PropelException
     * @throws Exception
     * @see        BaseObject::setDeleted()
     * @see        BaseObject::isDeleted()
     */
    public function delete(PropelPDO $con = null)
    {
        if ($this->isDeleted()) {
            throw new PropelException("This object has already been deleted.");
        }

        if ($con === null) {
            $con = Propel::getConnection(twSubscriptionMessageTypePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
        }

        $con->beginTransaction();
        try {
            $deleteQuery = twSubscriptionMessageTypeQuery::create()
                ->filterByPrimaryKey($this->getPrimaryKey());
            $ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BasetwSubscriptionMessageType:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			    return;
			  }
			}

            if ($ret) {
                $deleteQuery->delete($con);
                $this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BasetwSubscriptionMessageType:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

                $con->commit();
                $this->setDeleted(true);
            } else {
                $con->commit();
            }
        } catch (Exception $e) {
            $con->rollBack();
            throw $e;
        }
    }

    /**
     * Persists this object to the database.
     *
     * If the object is new, it inserts it; otherwise an update is performed.
     * All modified related objects will also be persisted in the doSave()
     * method.  This method wraps all precipitate database operations in a
     * single transaction.
     *
     * @param      PropelPDO $con
     * @return int             The number of rows affected by this insert/update and any referring fk objects' save() operations.
     * @throws PropelException
     * @throws Exception
     * @see        doSave()
     */
    public function save(PropelPDO $con = null)
    {
        if ($this->isDeleted()) {
            throw new PropelException("You cannot save an object that has been deleted.");
        }

        if ($con === null) {
            $con = Propel::getConnection(twSubscriptionMessageTypePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
        }

        $con->beginTransaction();
        $isInsert = $this->isNew();
        try {
            $ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BasetwSubscriptionMessageType:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			  	$con->commit();
			    return $affectedRows;
			  }
			}

            if ($isInsert) {
                $ret = $ret && $this->preInsert($con);
            } else {
                $ret = $ret && $this->preUpdate($con);
            }
            if ($ret) {
                $affectedRows = $this->doSave($con);
                if ($isInsert) {
                    $this->postInsert($con);
                } else {
                    $this->postUpdate($con);
                }
                $this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BasetwSubscriptionMessageType:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

                twSubscriptionMessageTypePeer::addInstanceToPool($this);
            } else {
                $affectedRows = 0;
            }
            $con->commit();

            return $affectedRows;
        } catch (Exception $e) {
            $con->rollBack();
            throw $e;
        }
    }

    /**
     * Performs the work of inserting or updating the row in the database.
     *
     * If the object is new, it inserts it; otherwise an update is performed.
     * All related objects are also updated in this method.
     *
     * @param      PropelPDO $con
     * @return int             The number of rows affected by this insert/update and any referring fk objects' save() operations.
     * @throws PropelException
     * @see        save()
     */
    protected function doSave(PropelPDO $con)
    {
        $affectedRows = 0; // initialize var to track total num of affected rows
        if (!$this->alreadyInSave) {
            $this->alreadyInSave = true;

            if ($this->isNew() || $this->isModified()) {
                // persist changes
                if ($this->isNew()) {
                    $this->doInsert($con);
                } else {
                    $this->doUpdate($con);
                }
                $affectedRows += 1;
                $this->resetModified();
            }

            if ($this->twSubscriptionMessageTypeI18nsScheduledForDeletion !== null) {
                if (!$this->twSubscriptionMessageTypeI18nsScheduledForDeletion->isEmpty()) {
                    twSubscriptionMessageTypeI18nQuery::create()
                        ->filterByPrimaryKeys($this->twSubscriptionMessageTypeI18nsScheduledForDeletion->getPrimaryKeys(false))
                        ->delete($con);
                    $this->twSubscriptionMessageTypeI18nsScheduledForDeletion = null;
                }
            }

            if ($this->colltwSubscriptionMessageTypeI18ns !== null) {
                foreach ($this->colltwSubscriptionMessageTypeI18ns as $referrerFK) {
          $referrerFK->settwSubscriptionMessageType($this);
                    if (!$referrerFK->isDeleted()) {
                        $affectedRows += $referrerFK->save($con);
                    }
                }
            }

            if ($this->twSubscriptionTemplatesScheduledForDeletion !== null) {
                if (!$this->twSubscriptionTemplatesScheduledForDeletion->isEmpty()) {
                    twSubscriptionTemplateQuery::create()
                        ->filterByPrimaryKeys($this->twSubscriptionTemplatesScheduledForDeletion->getPrimaryKeys(false))
                        ->delete($con);
                    $this->twSubscriptionTemplatesScheduledForDeletion = null;
                }
            }

            if ($this->colltwSubscriptionTemplates !== null) {
                foreach ($this->colltwSubscriptionTemplates as $referrerFK) {
                    if (!$referrerFK->isDeleted()) {
                        $affectedRows += $referrerFK->save($con);
                    }
                }
            }

            if ($this->twSubscriptionMessagesScheduledForDeletion !== null) {
                if (!$this->twSubscriptionMessagesScheduledForDeletion->isEmpty()) {
                    twSubscriptionMessageQuery::create()
                        ->filterByPrimaryKeys($this->twSubscriptionMessagesScheduledForDeletion->getPrimaryKeys(false))
                        ->delete($con);
                    $this->twSubscriptionMessagesScheduledForDeletion = null;
                }
            }

            if ($this->colltwSubscriptionMessages !== null) {
                foreach ($this->colltwSubscriptionMessages as $referrerFK) {
                    if (!$referrerFK->isDeleted()) {
                        $affectedRows += $referrerFK->save($con);
                    }
                }
            }

            if ($this->twSubscriptionListInvitationsScheduledForDeletion !== null) {
                if (!$this->twSubscriptionListInvitationsScheduledForDeletion->isEmpty()) {
                    twSubscriptionListInvitationQuery::create()
                        ->filterByPrimaryKeys($this->twSubscriptionListInvitationsScheduledForDeletion->getPrimaryKeys(false))
                        ->delete($con);
                    $this->twSubscriptionListInvitationsScheduledForDeletion = null;
                }
            }

            if ($this->colltwSubscriptionListInvitations !== null) {
                foreach ($this->colltwSubscriptionListInvitations as $referrerFK) {
                    if (!$referrerFK->isDeleted()) {
                        $affectedRows += $referrerFK->save($con);
                    }
                }
            }

            if ($this->twSubscriptionMailQueuesScheduledForDeletion !== null) {
                if (!$this->twSubscriptionMailQueuesScheduledForDeletion->isEmpty()) {
                    twSubscriptionMailQueueQuery::create()
                        ->filterByPrimaryKeys($this->twSubscriptionMailQueuesScheduledForDeletion->getPrimaryKeys(false))
                        ->delete($con);
                    $this->twSubscriptionMailQueuesScheduledForDeletion = null;
                }
            }

            if ($this->colltwSubscriptionMailQueues !== null) {
                foreach ($this->colltwSubscriptionMailQueues as $referrerFK) {
                    if (!$referrerFK->isDeleted()) {
                        $affectedRows += $referrerFK->save($con);
                    }
                }
            }

            $this->alreadyInSave = false;

        }

        return $affectedRows;
    } // doSave()

    /**
     * Insert the row in the database.
     *
     * @param      PropelPDO $con
     *
     * @throws PropelException
     * @see        doSave()
     */
    protected function doInsert(PropelPDO $con)
    {
        $modifiedColumns = array();
        $index = 0;

        $this->modifiedColumns[] = twSubscriptionMessageTypePeer::ID;
        if (null !== $this->id) {
            throw new PropelException('Cannot insert a value for auto-increment primary key (' . twSubscriptionMessageTypePeer::ID . ')');
        }

         // check the columns in natural order for more readable SQL queries
        if ($this->isColumnModified(twSubscriptionMessageTypePeer::ID)) {
            $modifiedColumns[':p' . $index++]  = '`ID`';
        }
        if ($this->isColumnModified(twSubscriptionMessageTypePeer::CODE)) {
            $modifiedColumns[':p' . $index++]  = '`CODE`';
        }

        $sql = sprintf(
            'INSERT INTO `tw_subscription_message_type` (%s) VALUES (%s)',
            implode(', ', $modifiedColumns),
            implode(', ', array_keys($modifiedColumns))
        );

        try {
            $stmt = $con->prepare($sql);
            foreach ($modifiedColumns as $identifier => $columnName) {
                switch ($columnName) {
                    case '`ID`':
						$stmt->bindValue($identifier, $this->id, PDO::PARAM_INT);
                        break;
                    case '`CODE`':
						$stmt->bindValue($identifier, $this->code, PDO::PARAM_STR);
                        break;
                }
            }
            $stmt->execute();
        } catch (Exception $e) {
            Propel::log($e->getMessage(), Propel::LOG_ERR);
            throw new PropelException(sprintf('Unable to execute INSERT statement [%s]', $sql), $e);
        }

        try {
			$pk = $con->lastInsertId();
        } catch (Exception $e) {
            throw new PropelException('Unable to get autoincrement id.', $e);
        }
        $this->setId($pk);

        $this->setNew(false);
    }

    /**
     * Update the row in the database.
     *
     * @param      PropelPDO $con
     *
     * @see        doSave()
     */
    protected function doUpdate(PropelPDO $con)
    {
        $selectCriteria = $this->buildPkeyCriteria();
        $valuesCriteria = $this->buildCriteria();
        BasePeer::doUpdate($selectCriteria, $valuesCriteria, $con);
    }

    /**
     * Array of ValidationFailed objects.
     * @var        array ValidationFailed[]
     */
    protected $validationFailures = array();

    /**
     * Gets any ValidationFailed objects that resulted from last call to validate().
     *
     *
     * @return array ValidationFailed[]
     * @see        validate()
     */
    public function getValidationFailures()
    {
        return $this->validationFailures;
    }

    /**
     * Validates the objects modified field values and all objects related to this table.
     *
     * If $columns is either a column name or an array of column names
     * only those columns are validated.
     *
     * @param      mixed $columns Column name or an array of column names.
     * @return boolean Whether all columns pass validation.
     * @see        doValidate()
     * @see        getValidationFailures()
     */
    public function validate($columns = null)
    {
        $res = $this->doValidate($columns);
        if ($res === true) {
            $this->validationFailures = array();

            return true;
        } else {
            $this->validationFailures = $res;

            return false;
        }
    }

    /**
     * This function performs the validation work for complex object models.
     *
     * In addition to checking the current object, all related objects will
     * also be validated.  If all pass then <code>true</code> is returned; otherwise
     * an aggreagated array of ValidationFailed objects will be returned.
     *
     * @param      array $columns Array of column names to validate.
     * @return mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
     */
    protected function doValidate($columns = null)
    {
        if (!$this->alreadyInValidation) {
            $this->alreadyInValidation = true;
            $retval = null;

            $failureMap = array();


            if (($retval = twSubscriptionMessageTypePeer::doValidate($this, $columns)) !== true) {
                $failureMap = array_merge($failureMap, $retval);
            }


                if ($this->colltwSubscriptionMessageTypeI18ns !== null) {
                    foreach ($this->colltwSubscriptionMessageTypeI18ns as $referrerFK) {
          $referrerFK->settwSubscriptionMessageType($this);
                        if (!$referrerFK->validate($columns)) {
                            $failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
                        }
                    }
                }

                if ($this->colltwSubscriptionTemplates !== null) {
                    foreach ($this->colltwSubscriptionTemplates as $referrerFK) {
                        if (!$referrerFK->validate($columns)) {
                            $failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
                        }
                    }
                }

                if ($this->colltwSubscriptionMessages !== null) {
                    foreach ($this->colltwSubscriptionMessages as $referrerFK) {
                        if (!$referrerFK->validate($columns)) {
                            $failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
                        }
                    }
                }

                if ($this->colltwSubscriptionListInvitations !== null) {
                    foreach ($this->colltwSubscriptionListInvitations as $referrerFK) {
                        if (!$referrerFK->validate($columns)) {
                            $failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
                        }
                    }
                }

                if ($this->colltwSubscriptionMailQueues !== null) {
                    foreach ($this->colltwSubscriptionMailQueues as $referrerFK) {
                        if (!$referrerFK->validate($columns)) {
                            $failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
                        }
                    }
                }


            $this->alreadyInValidation = false;
        }

        return (!empty($failureMap) ? $failureMap : true);
    }

    /**
     * Retrieves a field from the object by name passed in as a string.
     *
     * @param      string $name name
     * @param      string $type The type of fieldname the $name is of:
     *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
     *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
     *                     Defaults to BasePeer::TYPE_PHPNAME
     * @return mixed Value of field.
     */
    public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
    {
        $pos = twSubscriptionMessageTypePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
        $field = $this->getByPosition($pos);

        return $field;
    }

    /**
     * Retrieves a field from the object by Position as specified in the xml schema.
     * Zero-based.
     *
     * @param      int $pos position in xml schema
     * @return mixed Value of field at $pos
     */
    public function getByPosition($pos)
    {
        switch ($pos) {
            case 0:
                return $this->getId();
                break;
            case 1:
                return $this->getCode();
                break;
            default:
                return null;
                break;
        } // switch()
    }

    /**
     * Exports the object as an array.
     *
     * You can specify the key type of the array by passing one of the class
     * type constants.
     *
     * @param     string  $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
     *                    BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
     *                    Defaults to BasePeer::TYPE_PHPNAME.
     * @param     boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns. Defaults to TRUE.
     * @param     array $alreadyDumpedObjects List of objects to skip to avoid recursion
     * @param     boolean $includeForeignObjects (optional) Whether to include hydrated related objects. Default to FALSE.
     *
     * @return array an associative array containing the field names (as keys) and field values
     */
    public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true, $alreadyDumpedObjects = array(), $includeForeignObjects = false)
    {
        if (isset($alreadyDumpedObjects['twSubscriptionMessageType'][$this->getPrimaryKey()])) {
            return '*RECURSION*';
        }
        $alreadyDumpedObjects['twSubscriptionMessageType'][$this->getPrimaryKey()] = true;
        $keys = twSubscriptionMessageTypePeer::getFieldNames($keyType);
        $result = array(
            $keys[0] => $this->getId(),
            $keys[1] => $this->getCode(),
        );
        if ($includeForeignObjects) {
            if (null !== $this->colltwSubscriptionMessageTypeI18ns) {
                $result['twSubscriptionMessageTypeI18ns'] = $this->colltwSubscriptionMessageTypeI18ns->toArray(null, true, $keyType, $includeLazyLoadColumns, $alreadyDumpedObjects);
            }
            if (null !== $this->colltwSubscriptionTemplates) {
                $result['twSubscriptionTemplates'] = $this->colltwSubscriptionTemplates->toArray(null, true, $keyType, $includeLazyLoadColumns, $alreadyDumpedObjects);
            }
            if (null !== $this->colltwSubscriptionMessages) {
                $result['twSubscriptionMessages'] = $this->colltwSubscriptionMessages->toArray(null, true, $keyType, $includeLazyLoadColumns, $alreadyDumpedObjects);
            }
            if (null !== $this->colltwSubscriptionListInvitations) {
                $result['twSubscriptionListInvitations'] = $this->colltwSubscriptionListInvitations->toArray(null, true, $keyType, $includeLazyLoadColumns, $alreadyDumpedObjects);
            }
            if (null !== $this->colltwSubscriptionMailQueues) {
                $result['twSubscriptionMailQueues'] = $this->colltwSubscriptionMailQueues->toArray(null, true, $keyType, $includeLazyLoadColumns, $alreadyDumpedObjects);
            }
        }

        return $result;
    }

    /**
     * Sets a field from the object by name passed in as a string.
     *
     * @param      string $name peer name
     * @param      mixed $value field value
     * @param      string $type The type of fieldname the $name is of:
     *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
     *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
     *                     Defaults to BasePeer::TYPE_PHPNAME
     * @return void
     */
    public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
    {
        $pos = twSubscriptionMessageTypePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);

        $this->setByPosition($pos, $value);
    }

    /**
     * Sets a field from the object by Position as specified in the xml schema.
     * Zero-based.
     *
     * @param      int $pos position in xml schema
     * @param      mixed $value field value
     * @return void
     */
    public function setByPosition($pos, $value)
    {
        switch ($pos) {
            case 0:
                $this->setId($value);
                break;
            case 1:
                $this->setCode($value);
                break;
        } // switch()
    }

    /**
     * Populates the object using an array.
     *
     * This is particularly useful when populating an object from one of the
     * request arrays (e.g. $_POST).  This method goes through the column
     * names, checking to see whether a matching key exists in populated
     * array. If so the setByName() method is called for that column.
     *
     * You can specify the key type of the array by additionally passing one
     * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
     * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
     * The default key type is the column's BasePeer::TYPE_PHPNAME
     *
     * @param      array  $arr     An array to populate the object from.
     * @param      string $keyType The type of keys the array uses.
     * @return void
     */
    public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
    {
        $keys = twSubscriptionMessageTypePeer::getFieldNames($keyType);

        if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
        if (array_key_exists($keys[1], $arr)) $this->setCode($arr[$keys[1]]);
    }

    /**
     * Build a Criteria object containing the values of all modified columns in this object.
     *
     * @return Criteria The Criteria object containing all modified values.
     */
    public function buildCriteria()
    {
        $criteria = new Criteria(twSubscriptionMessageTypePeer::DATABASE_NAME);

        if ($this->isColumnModified(twSubscriptionMessageTypePeer::ID)) $criteria->add(twSubscriptionMessageTypePeer::ID, $this->id);
        if ($this->isColumnModified(twSubscriptionMessageTypePeer::CODE)) $criteria->add(twSubscriptionMessageTypePeer::CODE, $this->code);

        return $criteria;
    }

    /**
     * Builds a Criteria object containing the primary key for this object.
     *
     * Unlike buildCriteria() this method includes the primary key values regardless
     * of whether or not they have been modified.
     *
     * @return Criteria The Criteria object containing value(s) for primary key(s).
     */
    public function buildPkeyCriteria()
    {
        $criteria = new Criteria(twSubscriptionMessageTypePeer::DATABASE_NAME);
        $criteria->add(twSubscriptionMessageTypePeer::ID, $this->id);

        return $criteria;
    }

    /**
     * Returns the primary key for this object (row).
     * @return   int
     */
    public function getPrimaryKey()
    {
        return $this->getId();
    }

    /**
     * Generic method to set the primary key (id column).
     *
     * @param       int $key Primary key.
     * @return void
     */
    public function setPrimaryKey($key)
    {
        $this->setId($key);
    }

    /**
     * Returns true if the primary key for this object is null.
     * @return boolean
     */
    public function isPrimaryKeyNull()
    {

        return null === $this->getId();
    }

    /**
     * Sets contents of passed object to values from current object.
     *
     * If desired, this method can also make copies of all associated (fkey referrers)
     * objects.
     *
     * @param      object $copyObj An object of twSubscriptionMessageType (or compatible) type.
     * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
     * @param      boolean $makeNew Whether to reset autoincrement PKs and make the object new.
     * @throws PropelException
     */
    public function copyInto($copyObj, $deepCopy = false, $makeNew = true)
    {
        $copyObj->setCode($this->getCode());

        if ($deepCopy && !$this->startCopy) {
            // important: temporarily setNew(false) because this affects the behavior of
            // the getter/setter methods for fkey referrer objects.
            $copyObj->setNew(false);
            // store object hash to prevent cycle
            $this->startCopy = true;

            foreach ($this->gettwSubscriptionMessageTypeI18ns() as $relObj) {
                if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
                    $copyObj->addtwSubscriptionMessageTypeI18n($relObj->copy($deepCopy));
                }
            }

            foreach ($this->gettwSubscriptionTemplates() as $relObj) {
                if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
                    $copyObj->addtwSubscriptionTemplate($relObj->copy($deepCopy));
                }
            }

            foreach ($this->gettwSubscriptionMessages() as $relObj) {
                if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
                    $copyObj->addtwSubscriptionMessage($relObj->copy($deepCopy));
                }
            }

            foreach ($this->gettwSubscriptionListInvitations() as $relObj) {
                if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
                    $copyObj->addtwSubscriptionListInvitation($relObj->copy($deepCopy));
                }
            }

            foreach ($this->gettwSubscriptionMailQueues() as $relObj) {
                if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
                    $copyObj->addtwSubscriptionMailQueue($relObj->copy($deepCopy));
                }
            }

            //unflag object copy
            $this->startCopy = false;
        } // if ($deepCopy)

        if ($makeNew) {
            $copyObj->setNew(true);
            $copyObj->setId(NULL); // this is a auto-increment column, so set to default value
        }
    }

    /**
     * Makes a copy of this object that will be inserted as a new row in table when saved.
     * It creates a new object filling in the simple attributes, but skipping any primary
     * keys that are defined for the table.
     *
     * If desired, this method can also make copies of all associated (fkey referrers)
     * objects.
     *
     * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
     * @return                 twSubscriptionMessageType Clone of current object.
     * @throws PropelException
     */
    public function copy($deepCopy = false)
    {
        // we use get_class(), because this might be a subclass
        $clazz = get_class($this);
        $copyObj = new $clazz();
        $this->copyInto($copyObj, $deepCopy);

        return $copyObj;
    }

    /**
     * Returns a peer instance associated with this om.
     *
     * Since Peer classes are not to have any instance attributes, this method returns the
     * same instance for all member of this class. The method could therefore
     * be static, but this would prevent one from overriding the behavior.
     *
     * @return   twSubscriptionMessageTypePeer
     */
    public function getPeer()
    {
        if (self::$peer === null) {
            self::$peer = new twSubscriptionMessageTypePeer();
        }

        return self::$peer;
    }


    /**
     * Initializes a collection based on the name of a relation.
     * Avoids crafting an 'init[$relationName]s' method name
     * that wouldn't work when StandardEnglishPluralizer is used.
     *
     * @param      string $relationName The name of the relation to initialize
     * @return void
     */
    public function initRelation($relationName)
    {
        if ('twSubscriptionMessageTypeI18n' == $relationName) {
            $this->inittwSubscriptionMessageTypeI18ns();
        }
        if ('twSubscriptionTemplate' == $relationName) {
            $this->inittwSubscriptionTemplates();
        }
        if ('twSubscriptionMessage' == $relationName) {
            $this->inittwSubscriptionMessages();
        }
        if ('twSubscriptionListInvitation' == $relationName) {
            $this->inittwSubscriptionListInvitations();
        }
        if ('twSubscriptionMailQueue' == $relationName) {
            $this->inittwSubscriptionMailQueues();
        }
    }

    /**
     * Clears out the colltwSubscriptionMessageTypeI18ns collection
     *
     * This does not modify the database; however, it will remove any associated objects, causing
     * them to be refetched by subsequent calls to accessor method.
     *
     * @return void
     * @see        addtwSubscriptionMessageTypeI18ns()
     */
    public function cleartwSubscriptionMessageTypeI18ns()
    {
        $this->colltwSubscriptionMessageTypeI18ns = null; // important to set this to NULL since that means it is uninitialized
    }

    /**
     * Initializes the colltwSubscriptionMessageTypeI18ns collection.
     *
     * By default this just sets the colltwSubscriptionMessageTypeI18ns collection to an empty array (like clearcolltwSubscriptionMessageTypeI18ns());
     * however, you may wish to override this method in your stub class to provide setting appropriate
     * to your application -- for example, setting the initial array to the values stored in database.
     *
     * @param      boolean $overrideExisting If set to true, the method call initializes
     *                                        the collection even if it is not empty
     *
     * @return void
     */
    public function inittwSubscriptionMessageTypeI18ns($overrideExisting = true)
    {
        if (null !== $this->colltwSubscriptionMessageTypeI18ns && !$overrideExisting) {
            return;
        }
        $this->colltwSubscriptionMessageTypeI18ns = new PropelObjectCollection();
        $this->colltwSubscriptionMessageTypeI18ns->setModel('twSubscriptionMessageTypeI18n');
    }

    /**
     * Gets an array of twSubscriptionMessageTypeI18n objects which contain a foreign key that references this object.
     *
     * If the $criteria is not null, it is used to always fetch the results from the database.
     * Otherwise the results are fetched from the database the first time, then cached.
     * Next time the same method is called without $criteria, the cached collection is returned.
     * If this twSubscriptionMessageType is new, it will return
     * an empty collection or the current collection; the criteria is ignored on a new object.
     *
     * @param      Criteria $criteria optional Criteria object to narrow the query
     * @param      PropelPDO $con optional connection object
     * @return PropelObjectCollection|twSubscriptionMessageTypeI18n[] List of twSubscriptionMessageTypeI18n objects
     * @throws PropelException
     */
    public function gettwSubscriptionMessageTypeI18ns($criteria = null, PropelPDO $con = null)
    {
        if (null === $this->colltwSubscriptionMessageTypeI18ns || null !== $criteria) {
            if ($this->isNew() && null === $this->colltwSubscriptionMessageTypeI18ns) {
                // return empty collection
                $this->inittwSubscriptionMessageTypeI18ns();
            } else {
                $colltwSubscriptionMessageTypeI18ns = twSubscriptionMessageTypeI18nQuery::create(null, $criteria)
                    ->filterBytwSubscriptionMessageType($this)
                    ->find($con);
                if (null !== $criteria) {
                    return $colltwSubscriptionMessageTypeI18ns;
                }
                $this->colltwSubscriptionMessageTypeI18ns = $colltwSubscriptionMessageTypeI18ns;
            }
        }

        return $this->colltwSubscriptionMessageTypeI18ns;
    }

    /**
     * Sets a collection of twSubscriptionMessageTypeI18n objects related by a one-to-many relationship
     * to the current object.
     * It will also schedule objects for deletion based on a diff between old objects (aka persisted)
     * and new objects from the given Propel collection.
     *
     * @param      PropelCollection $twSubscriptionMessageTypeI18ns A Propel collection.
     * @param      PropelPDO $con Optional connection object
     */
    public function settwSubscriptionMessageTypeI18ns(PropelCollection $twSubscriptionMessageTypeI18ns, PropelPDO $con = null)
    {
        $this->twSubscriptionMessageTypeI18nsScheduledForDeletion = $this->gettwSubscriptionMessageTypeI18ns(new Criteria(), $con)->diff($twSubscriptionMessageTypeI18ns);

        foreach ($this->twSubscriptionMessageTypeI18nsScheduledForDeletion as $twSubscriptionMessageTypeI18nRemoved) {
            $twSubscriptionMessageTypeI18nRemoved->settwSubscriptionMessageType(null);
        }

        $this->colltwSubscriptionMessageTypeI18ns = null;
        foreach ($twSubscriptionMessageTypeI18ns as $twSubscriptionMessageTypeI18n) {
            $this->addtwSubscriptionMessageTypeI18n($twSubscriptionMessageTypeI18n);
        }

        $this->colltwSubscriptionMessageTypeI18ns = $twSubscriptionMessageTypeI18ns;
    }

    /**
     * Returns the number of related twSubscriptionMessageTypeI18n objects.
     *
     * @param      Criteria $criteria
     * @param      boolean $distinct
     * @param      PropelPDO $con
     * @return int             Count of related twSubscriptionMessageTypeI18n objects.
     * @throws PropelException
     */
    public function counttwSubscriptionMessageTypeI18ns(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
    {
        if (null === $this->colltwSubscriptionMessageTypeI18ns || null !== $criteria) {
            if ($this->isNew() && null === $this->colltwSubscriptionMessageTypeI18ns) {
                return 0;
            } else {
                $query = twSubscriptionMessageTypeI18nQuery::create(null, $criteria);
                if ($distinct) {
                    $query->distinct();
                }

                return $query
                    ->filterBytwSubscriptionMessageType($this)
                    ->count($con);
            }
        } else {
            return count($this->colltwSubscriptionMessageTypeI18ns);
        }
    }

    /**
     * Method called to associate a twSubscriptionMessageTypeI18n object to this object
     * through the twSubscriptionMessageTypeI18n foreign key attribute.
     *
     * @param    twSubscriptionMessageTypeI18n $l twSubscriptionMessageTypeI18n
     * @return   twSubscriptionMessageType The current object (for fluent API support)
     */
    public function addtwSubscriptionMessageTypeI18n(twSubscriptionMessageTypeI18n $l)
    {
        if ($this->colltwSubscriptionMessageTypeI18ns === null) {
            $this->inittwSubscriptionMessageTypeI18ns();
        }
        if (!$this->colltwSubscriptionMessageTypeI18ns->contains($l)) { // only add it if the **same** object is not already associated
            $this->doAddtwSubscriptionMessageTypeI18n($l);
        }

        return $this;
    }

    /**
     * @param	twSubscriptionMessageTypeI18n $twSubscriptionMessageTypeI18n The twSubscriptionMessageTypeI18n object to add.
     */
    protected function doAddtwSubscriptionMessageTypeI18n($twSubscriptionMessageTypeI18n)
    {
        $this->colltwSubscriptionMessageTypeI18ns[]= $twSubscriptionMessageTypeI18n;
        $twSubscriptionMessageTypeI18n->settwSubscriptionMessageType($this);
    }

    /**
     * @param	twSubscriptionMessageTypeI18n $twSubscriptionMessageTypeI18n The twSubscriptionMessageTypeI18n object to remove.
     */
    public function removetwSubscriptionMessageTypeI18n($twSubscriptionMessageTypeI18n)
    {
        if ($this->gettwSubscriptionMessageTypeI18ns()->contains($twSubscriptionMessageTypeI18n)) {
            $this->colltwSubscriptionMessageTypeI18ns->remove($this->colltwSubscriptionMessageTypeI18ns->search($twSubscriptionMessageTypeI18n));
            if (null === $this->twSubscriptionMessageTypeI18nsScheduledForDeletion) {
                $this->twSubscriptionMessageTypeI18nsScheduledForDeletion = clone $this->colltwSubscriptionMessageTypeI18ns;
                $this->twSubscriptionMessageTypeI18nsScheduledForDeletion->clear();
            }
            $this->twSubscriptionMessageTypeI18nsScheduledForDeletion[]= $twSubscriptionMessageTypeI18n;
            $twSubscriptionMessageTypeI18n->settwSubscriptionMessageType(null);
        }
    }

    /**
     * Clears out the colltwSubscriptionTemplates collection
     *
     * This does not modify the database; however, it will remove any associated objects, causing
     * them to be refetched by subsequent calls to accessor method.
     *
     * @return void
     * @see        addtwSubscriptionTemplates()
     */
    public function cleartwSubscriptionTemplates()
    {
        $this->colltwSubscriptionTemplates = null; // important to set this to NULL since that means it is uninitialized
    }

    /**
     * Initializes the colltwSubscriptionTemplates collection.
     *
     * By default this just sets the colltwSubscriptionTemplates collection to an empty array (like clearcolltwSubscriptionTemplates());
     * however, you may wish to override this method in your stub class to provide setting appropriate
     * to your application -- for example, setting the initial array to the values stored in database.
     *
     * @param      boolean $overrideExisting If set to true, the method call initializes
     *                                        the collection even if it is not empty
     *
     * @return void
     */
    public function inittwSubscriptionTemplates($overrideExisting = true)
    {
        if (null !== $this->colltwSubscriptionTemplates && !$overrideExisting) {
            return;
        }
        $this->colltwSubscriptionTemplates = new PropelObjectCollection();
        $this->colltwSubscriptionTemplates->setModel('twSubscriptionTemplate');
    }

    /**
     * Gets an array of twSubscriptionTemplate objects which contain a foreign key that references this object.
     *
     * If the $criteria is not null, it is used to always fetch the results from the database.
     * Otherwise the results are fetched from the database the first time, then cached.
     * Next time the same method is called without $criteria, the cached collection is returned.
     * If this twSubscriptionMessageType is new, it will return
     * an empty collection or the current collection; the criteria is ignored on a new object.
     *
     * @param      Criteria $criteria optional Criteria object to narrow the query
     * @param      PropelPDO $con optional connection object
     * @return PropelObjectCollection|twSubscriptionTemplate[] List of twSubscriptionTemplate objects
     * @throws PropelException
     */
    public function gettwSubscriptionTemplates($criteria = null, PropelPDO $con = null)
    {
        if (null === $this->colltwSubscriptionTemplates || null !== $criteria) {
            if ($this->isNew() && null === $this->colltwSubscriptionTemplates) {
                // return empty collection
                $this->inittwSubscriptionTemplates();
            } else {
                $colltwSubscriptionTemplates = twSubscriptionTemplateQuery::create(null, $criteria)
                    ->filterBytwSubscriptionMessageType($this)
                    ->find($con);
                if (null !== $criteria) {
                    return $colltwSubscriptionTemplates;
                }
                $this->colltwSubscriptionTemplates = $colltwSubscriptionTemplates;
            }
        }

        return $this->colltwSubscriptionTemplates;
    }

    /**
     * Sets a collection of twSubscriptionTemplate objects related by a one-to-many relationship
     * to the current object.
     * It will also schedule objects for deletion based on a diff between old objects (aka persisted)
     * and new objects from the given Propel collection.
     *
     * @param      PropelCollection $twSubscriptionTemplates A Propel collection.
     * @param      PropelPDO $con Optional connection object
     */
    public function settwSubscriptionTemplates(PropelCollection $twSubscriptionTemplates, PropelPDO $con = null)
    {
        $this->twSubscriptionTemplatesScheduledForDeletion = $this->gettwSubscriptionTemplates(new Criteria(), $con)->diff($twSubscriptionTemplates);

        foreach ($this->twSubscriptionTemplatesScheduledForDeletion as $twSubscriptionTemplateRemoved) {
            $twSubscriptionTemplateRemoved->settwSubscriptionMessageType(null);
        }

        $this->colltwSubscriptionTemplates = null;
        foreach ($twSubscriptionTemplates as $twSubscriptionTemplate) {
            $this->addtwSubscriptionTemplate($twSubscriptionTemplate);
        }

        $this->colltwSubscriptionTemplates = $twSubscriptionTemplates;
    }

    /**
     * Returns the number of related twSubscriptionTemplate objects.
     *
     * @param      Criteria $criteria
     * @param      boolean $distinct
     * @param      PropelPDO $con
     * @return int             Count of related twSubscriptionTemplate objects.
     * @throws PropelException
     */
    public function counttwSubscriptionTemplates(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
    {
        if (null === $this->colltwSubscriptionTemplates || null !== $criteria) {
            if ($this->isNew() && null === $this->colltwSubscriptionTemplates) {
                return 0;
            } else {
                $query = twSubscriptionTemplateQuery::create(null, $criteria);
                if ($distinct) {
                    $query->distinct();
                }

                return $query
                    ->filterBytwSubscriptionMessageType($this)
                    ->count($con);
            }
        } else {
            return count($this->colltwSubscriptionTemplates);
        }
    }

    /**
     * Method called to associate a twSubscriptionTemplate object to this object
     * through the twSubscriptionTemplate foreign key attribute.
     *
     * @param    twSubscriptionTemplate $l twSubscriptionTemplate
     * @return   twSubscriptionMessageType The current object (for fluent API support)
     */
    public function addtwSubscriptionTemplate(twSubscriptionTemplate $l)
    {
        if ($this->colltwSubscriptionTemplates === null) {
            $this->inittwSubscriptionTemplates();
        }
        if (!$this->colltwSubscriptionTemplates->contains($l)) { // only add it if the **same** object is not already associated
            $this->doAddtwSubscriptionTemplate($l);
        }

        return $this;
    }

    /**
     * @param	twSubscriptionTemplate $twSubscriptionTemplate The twSubscriptionTemplate object to add.
     */
    protected function doAddtwSubscriptionTemplate($twSubscriptionTemplate)
    {
        $this->colltwSubscriptionTemplates[]= $twSubscriptionTemplate;
        $twSubscriptionTemplate->settwSubscriptionMessageType($this);
    }

    /**
     * @param	twSubscriptionTemplate $twSubscriptionTemplate The twSubscriptionTemplate object to remove.
     */
    public function removetwSubscriptionTemplate($twSubscriptionTemplate)
    {
        if ($this->gettwSubscriptionTemplates()->contains($twSubscriptionTemplate)) {
            $this->colltwSubscriptionTemplates->remove($this->colltwSubscriptionTemplates->search($twSubscriptionTemplate));
            if (null === $this->twSubscriptionTemplatesScheduledForDeletion) {
                $this->twSubscriptionTemplatesScheduledForDeletion = clone $this->colltwSubscriptionTemplates;
                $this->twSubscriptionTemplatesScheduledForDeletion->clear();
            }
            $this->twSubscriptionTemplatesScheduledForDeletion[]= $twSubscriptionTemplate;
            $twSubscriptionTemplate->settwSubscriptionMessageType(null);
        }
    }

    /**
     * Clears out the colltwSubscriptionMessages collection
     *
     * This does not modify the database; however, it will remove any associated objects, causing
     * them to be refetched by subsequent calls to accessor method.
     *
     * @return void
     * @see        addtwSubscriptionMessages()
     */
    public function cleartwSubscriptionMessages()
    {
        $this->colltwSubscriptionMessages = null; // important to set this to NULL since that means it is uninitialized
    }

    /**
     * Initializes the colltwSubscriptionMessages collection.
     *
     * By default this just sets the colltwSubscriptionMessages collection to an empty array (like clearcolltwSubscriptionMessages());
     * however, you may wish to override this method in your stub class to provide setting appropriate
     * to your application -- for example, setting the initial array to the values stored in database.
     *
     * @param      boolean $overrideExisting If set to true, the method call initializes
     *                                        the collection even if it is not empty
     *
     * @return void
     */
    public function inittwSubscriptionMessages($overrideExisting = true)
    {
        if (null !== $this->colltwSubscriptionMessages && !$overrideExisting) {
            return;
        }
        $this->colltwSubscriptionMessages = new PropelObjectCollection();
        $this->colltwSubscriptionMessages->setModel('twSubscriptionMessage');
    }

    /**
     * Gets an array of twSubscriptionMessage objects which contain a foreign key that references this object.
     *
     * If the $criteria is not null, it is used to always fetch the results from the database.
     * Otherwise the results are fetched from the database the first time, then cached.
     * Next time the same method is called without $criteria, the cached collection is returned.
     * If this twSubscriptionMessageType is new, it will return
     * an empty collection or the current collection; the criteria is ignored on a new object.
     *
     * @param      Criteria $criteria optional Criteria object to narrow the query
     * @param      PropelPDO $con optional connection object
     * @return PropelObjectCollection|twSubscriptionMessage[] List of twSubscriptionMessage objects
     * @throws PropelException
     */
    public function gettwSubscriptionMessages($criteria = null, PropelPDO $con = null)
    {
        if (null === $this->colltwSubscriptionMessages || null !== $criteria) {
            if ($this->isNew() && null === $this->colltwSubscriptionMessages) {
                // return empty collection
                $this->inittwSubscriptionMessages();
            } else {
                $colltwSubscriptionMessages = twSubscriptionMessageQuery::create(null, $criteria)
                    ->filterBytwSubscriptionMessageType($this)
                    ->find($con);
                if (null !== $criteria) {
                    return $colltwSubscriptionMessages;
                }
                $this->colltwSubscriptionMessages = $colltwSubscriptionMessages;
            }
        }

        return $this->colltwSubscriptionMessages;
    }

    /**
     * Sets a collection of twSubscriptionMessage objects related by a one-to-many relationship
     * to the current object.
     * It will also schedule objects for deletion based on a diff between old objects (aka persisted)
     * and new objects from the given Propel collection.
     *
     * @param      PropelCollection $twSubscriptionMessages A Propel collection.
     * @param      PropelPDO $con Optional connection object
     */
    public function settwSubscriptionMessages(PropelCollection $twSubscriptionMessages, PropelPDO $con = null)
    {
        $this->twSubscriptionMessagesScheduledForDeletion = $this->gettwSubscriptionMessages(new Criteria(), $con)->diff($twSubscriptionMessages);

        foreach ($this->twSubscriptionMessagesScheduledForDeletion as $twSubscriptionMessageRemoved) {
            $twSubscriptionMessageRemoved->settwSubscriptionMessageType(null);
        }

        $this->colltwSubscriptionMessages = null;
        foreach ($twSubscriptionMessages as $twSubscriptionMessage) {
            $this->addtwSubscriptionMessage($twSubscriptionMessage);
        }

        $this->colltwSubscriptionMessages = $twSubscriptionMessages;
    }

    /**
     * Returns the number of related twSubscriptionMessage objects.
     *
     * @param      Criteria $criteria
     * @param      boolean $distinct
     * @param      PropelPDO $con
     * @return int             Count of related twSubscriptionMessage objects.
     * @throws PropelException
     */
    public function counttwSubscriptionMessages(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
    {
        if (null === $this->colltwSubscriptionMessages || null !== $criteria) {
            if ($this->isNew() && null === $this->colltwSubscriptionMessages) {
                return 0;
            } else {
                $query = twSubscriptionMessageQuery::create(null, $criteria);
                if ($distinct) {
                    $query->distinct();
                }

                return $query
                    ->filterBytwSubscriptionMessageType($this)
                    ->count($con);
            }
        } else {
            return count($this->colltwSubscriptionMessages);
        }
    }

    /**
     * Method called to associate a twSubscriptionMessage object to this object
     * through the twSubscriptionMessage foreign key attribute.
     *
     * @param    twSubscriptionMessage $l twSubscriptionMessage
     * @return   twSubscriptionMessageType The current object (for fluent API support)
     */
    public function addtwSubscriptionMessage(twSubscriptionMessage $l)
    {
        if ($this->colltwSubscriptionMessages === null) {
            $this->inittwSubscriptionMessages();
        }
        if (!$this->colltwSubscriptionMessages->contains($l)) { // only add it if the **same** object is not already associated
            $this->doAddtwSubscriptionMessage($l);
        }

        return $this;
    }

    /**
     * @param	twSubscriptionMessage $twSubscriptionMessage The twSubscriptionMessage object to add.
     */
    protected function doAddtwSubscriptionMessage($twSubscriptionMessage)
    {
        $this->colltwSubscriptionMessages[]= $twSubscriptionMessage;
        $twSubscriptionMessage->settwSubscriptionMessageType($this);
    }

    /**
     * @param	twSubscriptionMessage $twSubscriptionMessage The twSubscriptionMessage object to remove.
     */
    public function removetwSubscriptionMessage($twSubscriptionMessage)
    {
        if ($this->gettwSubscriptionMessages()->contains($twSubscriptionMessage)) {
            $this->colltwSubscriptionMessages->remove($this->colltwSubscriptionMessages->search($twSubscriptionMessage));
            if (null === $this->twSubscriptionMessagesScheduledForDeletion) {
                $this->twSubscriptionMessagesScheduledForDeletion = clone $this->colltwSubscriptionMessages;
                $this->twSubscriptionMessagesScheduledForDeletion->clear();
            }
            $this->twSubscriptionMessagesScheduledForDeletion[]= $twSubscriptionMessage;
            $twSubscriptionMessage->settwSubscriptionMessageType(null);
        }
    }

    /**
     * Clears out the colltwSubscriptionListInvitations collection
     *
     * This does not modify the database; however, it will remove any associated objects, causing
     * them to be refetched by subsequent calls to accessor method.
     *
     * @return void
     * @see        addtwSubscriptionListInvitations()
     */
    public function cleartwSubscriptionListInvitations()
    {
        $this->colltwSubscriptionListInvitations = null; // important to set this to NULL since that means it is uninitialized
    }

    /**
     * Initializes the colltwSubscriptionListInvitations collection.
     *
     * By default this just sets the colltwSubscriptionListInvitations collection to an empty array (like clearcolltwSubscriptionListInvitations());
     * however, you may wish to override this method in your stub class to provide setting appropriate
     * to your application -- for example, setting the initial array to the values stored in database.
     *
     * @param      boolean $overrideExisting If set to true, the method call initializes
     *                                        the collection even if it is not empty
     *
     * @return void
     */
    public function inittwSubscriptionListInvitations($overrideExisting = true)
    {
        if (null !== $this->colltwSubscriptionListInvitations && !$overrideExisting) {
            return;
        }
        $this->colltwSubscriptionListInvitations = new PropelObjectCollection();
        $this->colltwSubscriptionListInvitations->setModel('twSubscriptionListInvitation');
    }

    /**
     * Gets an array of twSubscriptionListInvitation objects which contain a foreign key that references this object.
     *
     * If the $criteria is not null, it is used to always fetch the results from the database.
     * Otherwise the results are fetched from the database the first time, then cached.
     * Next time the same method is called without $criteria, the cached collection is returned.
     * If this twSubscriptionMessageType is new, it will return
     * an empty collection or the current collection; the criteria is ignored on a new object.
     *
     * @param      Criteria $criteria optional Criteria object to narrow the query
     * @param      PropelPDO $con optional connection object
     * @return PropelObjectCollection|twSubscriptionListInvitation[] List of twSubscriptionListInvitation objects
     * @throws PropelException
     */
    public function gettwSubscriptionListInvitations($criteria = null, PropelPDO $con = null)
    {
        if (null === $this->colltwSubscriptionListInvitations || null !== $criteria) {
            if ($this->isNew() && null === $this->colltwSubscriptionListInvitations) {
                // return empty collection
                $this->inittwSubscriptionListInvitations();
            } else {
                $colltwSubscriptionListInvitations = twSubscriptionListInvitationQuery::create(null, $criteria)
                    ->filterBytwSubscriptionMessageType($this)
                    ->find($con);
                if (null !== $criteria) {
                    return $colltwSubscriptionListInvitations;
                }
                $this->colltwSubscriptionListInvitations = $colltwSubscriptionListInvitations;
            }
        }

        return $this->colltwSubscriptionListInvitations;
    }

    /**
     * Sets a collection of twSubscriptionListInvitation objects related by a one-to-many relationship
     * to the current object.
     * It will also schedule objects for deletion based on a diff between old objects (aka persisted)
     * and new objects from the given Propel collection.
     *
     * @param      PropelCollection $twSubscriptionListInvitations A Propel collection.
     * @param      PropelPDO $con Optional connection object
     */
    public function settwSubscriptionListInvitations(PropelCollection $twSubscriptionListInvitations, PropelPDO $con = null)
    {
        $this->twSubscriptionListInvitationsScheduledForDeletion = $this->gettwSubscriptionListInvitations(new Criteria(), $con)->diff($twSubscriptionListInvitations);

        foreach ($this->twSubscriptionListInvitationsScheduledForDeletion as $twSubscriptionListInvitationRemoved) {
            $twSubscriptionListInvitationRemoved->settwSubscriptionMessageType(null);
        }

        $this->colltwSubscriptionListInvitations = null;
        foreach ($twSubscriptionListInvitations as $twSubscriptionListInvitation) {
            $this->addtwSubscriptionListInvitation($twSubscriptionListInvitation);
        }

        $this->colltwSubscriptionListInvitations = $twSubscriptionListInvitations;
    }

    /**
     * Returns the number of related twSubscriptionListInvitation objects.
     *
     * @param      Criteria $criteria
     * @param      boolean $distinct
     * @param      PropelPDO $con
     * @return int             Count of related twSubscriptionListInvitation objects.
     * @throws PropelException
     */
    public function counttwSubscriptionListInvitations(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
    {
        if (null === $this->colltwSubscriptionListInvitations || null !== $criteria) {
            if ($this->isNew() && null === $this->colltwSubscriptionListInvitations) {
                return 0;
            } else {
                $query = twSubscriptionListInvitationQuery::create(null, $criteria);
                if ($distinct) {
                    $query->distinct();
                }

                return $query
                    ->filterBytwSubscriptionMessageType($this)
                    ->count($con);
            }
        } else {
            return count($this->colltwSubscriptionListInvitations);
        }
    }

    /**
     * Method called to associate a twSubscriptionListInvitation object to this object
     * through the twSubscriptionListInvitation foreign key attribute.
     *
     * @param    twSubscriptionListInvitation $l twSubscriptionListInvitation
     * @return   twSubscriptionMessageType The current object (for fluent API support)
     */
    public function addtwSubscriptionListInvitation(twSubscriptionListInvitation $l)
    {
        if ($this->colltwSubscriptionListInvitations === null) {
            $this->inittwSubscriptionListInvitations();
        }
        if (!$this->colltwSubscriptionListInvitations->contains($l)) { // only add it if the **same** object is not already associated
            $this->doAddtwSubscriptionListInvitation($l);
        }

        return $this;
    }

    /**
     * @param	twSubscriptionListInvitation $twSubscriptionListInvitation The twSubscriptionListInvitation object to add.
     */
    protected function doAddtwSubscriptionListInvitation($twSubscriptionListInvitation)
    {
        $this->colltwSubscriptionListInvitations[]= $twSubscriptionListInvitation;
        $twSubscriptionListInvitation->settwSubscriptionMessageType($this);
    }

    /**
     * @param	twSubscriptionListInvitation $twSubscriptionListInvitation The twSubscriptionListInvitation object to remove.
     */
    public function removetwSubscriptionListInvitation($twSubscriptionListInvitation)
    {
        if ($this->gettwSubscriptionListInvitations()->contains($twSubscriptionListInvitation)) {
            $this->colltwSubscriptionListInvitations->remove($this->colltwSubscriptionListInvitations->search($twSubscriptionListInvitation));
            if (null === $this->twSubscriptionListInvitationsScheduledForDeletion) {
                $this->twSubscriptionListInvitationsScheduledForDeletion = clone $this->colltwSubscriptionListInvitations;
                $this->twSubscriptionListInvitationsScheduledForDeletion->clear();
            }
            $this->twSubscriptionListInvitationsScheduledForDeletion[]= $twSubscriptionListInvitation;
            $twSubscriptionListInvitation->settwSubscriptionMessageType(null);
        }
    }


    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this twSubscriptionMessageType is new, it will return
     * an empty collection; or if this twSubscriptionMessageType has previously
     * been saved, it will retrieve related twSubscriptionListInvitations from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in twSubscriptionMessageType.
     *
     * @param      Criteria $criteria optional Criteria object to narrow the query
     * @param      PropelPDO $con optional connection object
     * @param      string $join_behavior optional join type to use (defaults to Criteria::LEFT_JOIN)
     * @return PropelObjectCollection|twSubscriptionListInvitation[] List of twSubscriptionListInvitation objects
     */
    public function gettwSubscriptionListInvitationsJointwSubscriptionList($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
    {
        $query = twSubscriptionListInvitationQuery::create(null, $criteria);
        $query->joinWith('twSubscriptionList', $join_behavior);

        return $this->gettwSubscriptionListInvitations($query, $con);
    }

    /**
     * Clears out the colltwSubscriptionMailQueues collection
     *
     * This does not modify the database; however, it will remove any associated objects, causing
     * them to be refetched by subsequent calls to accessor method.
     *
     * @return void
     * @see        addtwSubscriptionMailQueues()
     */
    public function cleartwSubscriptionMailQueues()
    {
        $this->colltwSubscriptionMailQueues = null; // important to set this to NULL since that means it is uninitialized
    }

    /**
     * Initializes the colltwSubscriptionMailQueues collection.
     *
     * By default this just sets the colltwSubscriptionMailQueues collection to an empty array (like clearcolltwSubscriptionMailQueues());
     * however, you may wish to override this method in your stub class to provide setting appropriate
     * to your application -- for example, setting the initial array to the values stored in database.
     *
     * @param      boolean $overrideExisting If set to true, the method call initializes
     *                                        the collection even if it is not empty
     *
     * @return void
     */
    public function inittwSubscriptionMailQueues($overrideExisting = true)
    {
        if (null !== $this->colltwSubscriptionMailQueues && !$overrideExisting) {
            return;
        }
        $this->colltwSubscriptionMailQueues = new PropelObjectCollection();
        $this->colltwSubscriptionMailQueues->setModel('twSubscriptionMailQueue');
    }

    /**
     * Gets an array of twSubscriptionMailQueue objects which contain a foreign key that references this object.
     *
     * If the $criteria is not null, it is used to always fetch the results from the database.
     * Otherwise the results are fetched from the database the first time, then cached.
     * Next time the same method is called without $criteria, the cached collection is returned.
     * If this twSubscriptionMessageType is new, it will return
     * an empty collection or the current collection; the criteria is ignored on a new object.
     *
     * @param      Criteria $criteria optional Criteria object to narrow the query
     * @param      PropelPDO $con optional connection object
     * @return PropelObjectCollection|twSubscriptionMailQueue[] List of twSubscriptionMailQueue objects
     * @throws PropelException
     */
    public function gettwSubscriptionMailQueues($criteria = null, PropelPDO $con = null)
    {
        if (null === $this->colltwSubscriptionMailQueues || null !== $criteria) {
            if ($this->isNew() && null === $this->colltwSubscriptionMailQueues) {
                // return empty collection
                $this->inittwSubscriptionMailQueues();
            } else {
                $colltwSubscriptionMailQueues = twSubscriptionMailQueueQuery::create(null, $criteria)
                    ->filterBytwSubscriptionMessageType($this)
                    ->find($con);
                if (null !== $criteria) {
                    return $colltwSubscriptionMailQueues;
                }
                $this->colltwSubscriptionMailQueues = $colltwSubscriptionMailQueues;
            }
        }

        return $this->colltwSubscriptionMailQueues;
    }

    /**
     * Sets a collection of twSubscriptionMailQueue objects related by a one-to-many relationship
     * to the current object.
     * It will also schedule objects for deletion based on a diff between old objects (aka persisted)
     * and new objects from the given Propel collection.
     *
     * @param      PropelCollection $twSubscriptionMailQueues A Propel collection.
     * @param      PropelPDO $con Optional connection object
     */
    public function settwSubscriptionMailQueues(PropelCollection $twSubscriptionMailQueues, PropelPDO $con = null)
    {
        $this->twSubscriptionMailQueuesScheduledForDeletion = $this->gettwSubscriptionMailQueues(new Criteria(), $con)->diff($twSubscriptionMailQueues);

        foreach ($this->twSubscriptionMailQueuesScheduledForDeletion as $twSubscriptionMailQueueRemoved) {
            $twSubscriptionMailQueueRemoved->settwSubscriptionMessageType(null);
        }

        $this->colltwSubscriptionMailQueues = null;
        foreach ($twSubscriptionMailQueues as $twSubscriptionMailQueue) {
            $this->addtwSubscriptionMailQueue($twSubscriptionMailQueue);
        }

        $this->colltwSubscriptionMailQueues = $twSubscriptionMailQueues;
    }

    /**
     * Returns the number of related twSubscriptionMailQueue objects.
     *
     * @param      Criteria $criteria
     * @param      boolean $distinct
     * @param      PropelPDO $con
     * @return int             Count of related twSubscriptionMailQueue objects.
     * @throws PropelException
     */
    public function counttwSubscriptionMailQueues(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
    {
        if (null === $this->colltwSubscriptionMailQueues || null !== $criteria) {
            if ($this->isNew() && null === $this->colltwSubscriptionMailQueues) {
                return 0;
            } else {
                $query = twSubscriptionMailQueueQuery::create(null, $criteria);
                if ($distinct) {
                    $query->distinct();
                }

                return $query
                    ->filterBytwSubscriptionMessageType($this)
                    ->count($con);
            }
        } else {
            return count($this->colltwSubscriptionMailQueues);
        }
    }

    /**
     * Method called to associate a twSubscriptionMailQueue object to this object
     * through the twSubscriptionMailQueue foreign key attribute.
     *
     * @param    twSubscriptionMailQueue $l twSubscriptionMailQueue
     * @return   twSubscriptionMessageType The current object (for fluent API support)
     */
    public function addtwSubscriptionMailQueue(twSubscriptionMailQueue $l)
    {
        if ($this->colltwSubscriptionMailQueues === null) {
            $this->inittwSubscriptionMailQueues();
        }
        if (!$this->colltwSubscriptionMailQueues->contains($l)) { // only add it if the **same** object is not already associated
            $this->doAddtwSubscriptionMailQueue($l);
        }

        return $this;
    }

    /**
     * @param	twSubscriptionMailQueue $twSubscriptionMailQueue The twSubscriptionMailQueue object to add.
     */
    protected function doAddtwSubscriptionMailQueue($twSubscriptionMailQueue)
    {
        $this->colltwSubscriptionMailQueues[]= $twSubscriptionMailQueue;
        $twSubscriptionMailQueue->settwSubscriptionMessageType($this);
    }

    /**
     * @param	twSubscriptionMailQueue $twSubscriptionMailQueue The twSubscriptionMailQueue object to remove.
     */
    public function removetwSubscriptionMailQueue($twSubscriptionMailQueue)
    {
        if ($this->gettwSubscriptionMailQueues()->contains($twSubscriptionMailQueue)) {
            $this->colltwSubscriptionMailQueues->remove($this->colltwSubscriptionMailQueues->search($twSubscriptionMailQueue));
            if (null === $this->twSubscriptionMailQueuesScheduledForDeletion) {
                $this->twSubscriptionMailQueuesScheduledForDeletion = clone $this->colltwSubscriptionMailQueues;
                $this->twSubscriptionMailQueuesScheduledForDeletion->clear();
            }
            $this->twSubscriptionMailQueuesScheduledForDeletion[]= $twSubscriptionMailQueue;
            $twSubscriptionMailQueue->settwSubscriptionMessageType(null);
        }
    }


    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this twSubscriptionMessageType is new, it will return
     * an empty collection; or if this twSubscriptionMessageType has previously
     * been saved, it will retrieve related twSubscriptionMailQueues from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in twSubscriptionMessageType.
     *
     * @param      Criteria $criteria optional Criteria object to narrow the query
     * @param      PropelPDO $con optional connection object
     * @param      string $join_behavior optional join type to use (defaults to Criteria::LEFT_JOIN)
     * @return PropelObjectCollection|twSubscriptionMailQueue[] List of twSubscriptionMailQueue objects
     */
    public function gettwSubscriptionMailQueuesJointwSubscriptionMailing($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
    {
        $query = twSubscriptionMailQueueQuery::create(null, $criteria);
        $query->joinWith('twSubscriptionMailing', $join_behavior);

        return $this->gettwSubscriptionMailQueues($query, $con);
    }


    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this twSubscriptionMessageType is new, it will return
     * an empty collection; or if this twSubscriptionMessageType has previously
     * been saved, it will retrieve related twSubscriptionMailQueues from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in twSubscriptionMessageType.
     *
     * @param      Criteria $criteria optional Criteria object to narrow the query
     * @param      PropelPDO $con optional connection object
     * @param      string $join_behavior optional join type to use (defaults to Criteria::LEFT_JOIN)
     * @return PropelObjectCollection|twSubscriptionMailQueue[] List of twSubscriptionMailQueue objects
     */
    public function gettwSubscriptionMailQueuesJointwSubscriptionMessage($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
    {
        $query = twSubscriptionMailQueueQuery::create(null, $criteria);
        $query->joinWith('twSubscriptionMessage', $join_behavior);

        return $this->gettwSubscriptionMailQueues($query, $con);
    }


    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this twSubscriptionMessageType is new, it will return
     * an empty collection; or if this twSubscriptionMessageType has previously
     * been saved, it will retrieve related twSubscriptionMailQueues from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in twSubscriptionMessageType.
     *
     * @param      Criteria $criteria optional Criteria object to narrow the query
     * @param      PropelPDO $con optional connection object
     * @param      string $join_behavior optional join type to use (defaults to Criteria::LEFT_JOIN)
     * @return PropelObjectCollection|twSubscriptionMailQueue[] List of twSubscriptionMailQueue objects
     */
    public function gettwSubscriptionMailQueuesJointwSubscriptionList($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
    {
        $query = twSubscriptionMailQueueQuery::create(null, $criteria);
        $query->joinWith('twSubscriptionList', $join_behavior);

        return $this->gettwSubscriptionMailQueues($query, $con);
    }

    /**
     * Clears the current object and sets all attributes to their default values
     */
    public function clear()
    {
        $this->id = null;
        $this->code = null;
        $this->alreadyInSave = false;
        $this->alreadyInValidation = false;
        $this->clearAllReferences();
        $this->resetModified();
        $this->setNew(true);
        $this->setDeleted(false);
    }

    /**
     * Resets all references to other model objects or collections of model objects.
     *
     * This method is a user-space workaround for PHP's inability to garbage collect
     * objects with circular references (even in PHP 5.3). This is currently necessary
     * when using Propel in certain daemon or large-volumne/high-memory operations.
     *
     * @param      boolean $deep Whether to also clear the references on all referrer objects.
     */
    public function clearAllReferences($deep = false)
    {
        if ($deep) {
            if ($this->colltwSubscriptionMessageTypeI18ns) {
                foreach ($this->colltwSubscriptionMessageTypeI18ns as $o) {
                    $o->clearAllReferences($deep);
                }
            }
            if ($this->colltwSubscriptionTemplates) {
                foreach ($this->colltwSubscriptionTemplates as $o) {
                    $o->clearAllReferences($deep);
                }
            }
            if ($this->colltwSubscriptionMessages) {
                foreach ($this->colltwSubscriptionMessages as $o) {
                    $o->clearAllReferences($deep);
                }
            }
            if ($this->colltwSubscriptionListInvitations) {
                foreach ($this->colltwSubscriptionListInvitations as $o) {
                    $o->clearAllReferences($deep);
                }
            }
            if ($this->colltwSubscriptionMailQueues) {
                foreach ($this->colltwSubscriptionMailQueues as $o) {
                    $o->clearAllReferences($deep);
                }
            }
        } // if ($deep)

        if ($this->colltwSubscriptionMessageTypeI18ns instanceof PropelCollection) {
            $this->colltwSubscriptionMessageTypeI18ns->clearIterator();
        }
        $this->colltwSubscriptionMessageTypeI18ns = null;
        if ($this->colltwSubscriptionTemplates instanceof PropelCollection) {
            $this->colltwSubscriptionTemplates->clearIterator();
        }
        $this->colltwSubscriptionTemplates = null;
        if ($this->colltwSubscriptionMessages instanceof PropelCollection) {
            $this->colltwSubscriptionMessages->clearIterator();
        }
        $this->colltwSubscriptionMessages = null;
        if ($this->colltwSubscriptionListInvitations instanceof PropelCollection) {
            $this->colltwSubscriptionListInvitations->clearIterator();
        }
        $this->colltwSubscriptionListInvitations = null;
        if ($this->colltwSubscriptionMailQueues instanceof PropelCollection) {
            $this->colltwSubscriptionMailQueues->clearIterator();
        }
        $this->colltwSubscriptionMailQueues = null;
    }

    /**
     * Return the string representation of this object
     *
     * @return string
     */
    public function __toString()
    {
        return (string) $this->exportTo(twSubscriptionMessageTypePeer::DEFAULT_STRING_FORMAT);
    }

	// symfony_i18n behavior
	
	/**
	 * Returns the culture.
	 *
	 * @return string The culture
	 */
	public function getCulture()
	{
	  return $this->culture;
	}
	
	/**
	 * Sets the culture.
	 *
	 * @param string  The culture to set
	 *
	 * @return twSubscriptionMessageType
	 */
	public function setCulture($culture)
	{
	  $this->culture = $culture;
	  return $this;
	}
	
	/**
	 * Returns the "name" value from the current {@link twSubscriptionMessageTypeI18n}.
	 */
	public function getName($culture = null)
	{
	  return $this->getCurrenttwSubscriptionMessageTypeI18n($culture)->getName();
	}
	
	/**
	 * Sets the "name" value of the current {@link twSubscriptionMessageTypeI18n}.
	 *
	 * @return twSubscriptionMessageType
	 */
	public function setName($value, $culture = null)
	{
	  $this->getCurrenttwSubscriptionMessageTypeI18n($culture)->setName($value);
	  return $this;
	}
	
	/**
	 * Returns the current translation.
	 *
	 * @return twSubscriptionMessageTypeI18n
	 */
	public function getCurrenttwSubscriptionMessageTypeI18n($culture = null)
	{
	  if (null === $culture)
	  {
	    $culture = null === $this->culture ? sfPropel::getDefaultCulture() : $this->culture;
	  }
	
	  if (!isset($this->current_i18n[$culture]))
	  {
	    $object = $this->isNew() ? null : twSubscriptionMessageTypeI18nPeer::retrieveByPK($this->getPrimaryKey(), $culture);
	    if ($object)
	    {
	      $this->settwSubscriptionMessageTypeI18nForCulture($object, $culture);
	    }
	    else
	    {
	      $this->settwSubscriptionMessageTypeI18nForCulture(new twSubscriptionMessageTypeI18n(), $culture);
	      $this->current_i18n[$culture]->setCulture($culture);
	    }
	  }
	
	  return $this->current_i18n[$culture];
	}
	
	/**
	 * Sets the translation object for a culture.
	 */
	public function settwSubscriptionMessageTypeI18nForCulture(twSubscriptionMessageTypeI18n $object, $culture)
	{
	  $this->current_i18n[$culture] = $object;
	  $this->addtwSubscriptionMessageTypeI18n($object);
	}

    /**
     * Catches calls to virtual methods
     */
    public function __call($name, $params)
    {
        
		// symfony_behaviors behavior
		if ($callable = sfMixer::getCallable('BasetwSubscriptionMessageType:' . $name))
		{
		  array_unshift($params, $this);
		  return call_user_func_array($callable, $params);
		}


        return parent::__call($name, $params);
    }

} // BasetwSubscriptionMessageType
