<?php



/**
 * Skeleton subclass for performing query and update operations on the 'tw_subscription_mail_queue' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.5.3 on:
 *
 * Wed Sep 21 16:50:38 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.plugins.twSubscriptionPlugin.lib.model
 */
class twSubscriptionMailQueueQuery extends BasetwSubscriptionMailQueueQuery
{
	static public function getMailingQueue(PropelPDO $connection)
	{
		$sth = $connection->prepare('
			SELECT id,
				mailing_id,
				message_type,
				subject,
				message,
				from_address,
				from_name,
				smtp_host,
				smtp_port,
				smtp_encr,
				smtp_user,
				smtp_pass,
				r_email,
				r_name,
				un_sub_code,
				un_sub_link,
				sub_base_url,
				web_base_url,
				time_to_send
			FROM tw_subscription_mail_queue
			WHERE time_to_send < NOW()
		');
		$sth->execute();

		return $sth->fetchAll(PDO::FETCH_ASSOC);
	}

	static public function delFromQueue(PropelPDO $connection, $row)
	{
		$stmt = $connection->prepare('
					INSERT INTO tw_subscription_mail_sent
						(mailing_id, time_to_send, sender, r_email, body, created_at)
					VALUES
						(:mailing_id, :time_to_send, :sender, :r_email, :body, NOW())
					');

		$stmt->bindParam(':mailing_id', $row['mailing_id']);
		$stmt->bindParam(':time_to_send', $row['time_to_send']);
		$stmt->bindParam(':sender', $row['from_address']);
		$stmt->bindParam(':r_email', $row['r_email']);
		$stmt->bindParam(':body', $row['message']);
		$stmt->execute();

		$stmt = $connection->prepare('DELETE FROM tw_subscription_mail_queue WHERE id = :id');
		$stmt->bindParam(':id', $row['id']);
		$stmt->execute();

	}
} // twSubscriptionMailQueueQuery
